// The Lantern Trail in Vietnamese. English source strings are the keys (and the fallback).
// Friends say "mình/bạn"; Juniper and Old Fog speak as elders ("ta"); Hazel writes as "bà" to "con".
export const VI = {
  // ---------------------------------------------------------------- story
  'The morning after Lantern Night, a little map came floating down with Hazel’s reply.': 'Sáng hôm sau Đêm Đèn Lồng, một tấm bản đồ nhỏ bay xuống cùng lá thư hồi âm của bà Hazel.',
  'Fernhollow! Hazel’s map says the trail home starts there.': 'Fernhollow! Bản đồ của bà nói con đường về nhà bắt đầu từ đó.',
  'The friends crossed the lantern bridge together, until a gust of silver mist swept them apart.': 'Các bạn cùng nhau đi qua cây cầu đèn lồng, cho đến khi một làn sương bạc thổi tới cuốn mỗi người một ngả.',
  'Momo? Nori? Everyone? …Okay. One step at a time.': 'Momo? Nori? Mọi người ơi? …Được rồi. Từng bước một thôi.',
  'Find your friends. Calm the lonely mist. Light the waystones so Hazel can find her way home.': 'Hãy tìm các bạn. Vỗ về những làn sương cô đơn. Thắp sáng các đèn đá dẫn đường để bà Hazel tìm được lối về.',
  'FERNHOLLOW · Waystones ahead. Please be gentle with the mist. — H.': 'FERNHOLLOW · Phía trước là đèn đá dẫn đường. Hãy dịu dàng với sương nhé. — H.',
  'A Mistling! It looks… sad.': 'Một Bé Sương! Trông nó… buồn quá.',
  'Mistlings are lonely wisps of fog. A warm hug is the only way to calm one.': 'Bé Sương là những làn sương nhỏ cô đơn. Chỉ có một cái ôm ấm áp mới làm chúng dịu lại.',
  'It turned into a firefly! I think it wants to come along.': 'Nó biến thành đom đóm rồi! Hình như nó muốn đi cùng mình.',
  'The waystone is cold. Something nearby is still too gloomy for it to light.': 'Đèn đá còn lạnh. Có gì đó gần đây vẫn còn u ám quá nên đèn chưa sáng được.',
  'The waystone glows. Everyone feels warm again, and your journey is saved here.': 'Đèn đá bừng sáng. Mọi người thấy ấm áp trở lại, và hành trình đã được lưu ở đây.',
  'The waystone glows. The mist on the bridge melts away like breath on a window.': 'Đèn đá bừng sáng. Màn sương trên cầu tan đi như hơi thở trên ô cửa kính.',
  'Hazel’s lights still work! Hold on, everyone, I’m coming.': 'Đèn của bà vẫn còn sáng! Mọi người chờ nhé, mình đến đây.',
  'A thick wall of mist hangs over the bridge. Something warm might clear it.': 'Một bức tường sương dày phủ kín cây cầu. Có lẽ thứ gì đó ấm áp sẽ làm nó tan.',
  'Pip! Oh, Pip! They won’t let me finish my tea!': 'Pip! Ôi, Pip! Tụi nó không cho mình uống hết tách trà!',
  'Hold on, Momo. We’ll calm them together!': 'Cố lên Momo. Mình cùng vỗ về tụi nó nhé!',
  'Thank you. My paws are still shaking.': 'Cảm ơn bạn. Chân mình vẫn còn run.',
  'Here, moonflower tea for the road. It warms everything it touches.': 'Đây, trà hoa trăng mang theo đường. Nó sưởi ấm mọi thứ nó chạm vào.',
  'Momo joined! Moonflower Tea heals the whole party. Its steam thins the mist on the next bridge.': 'Momo đã nhập hội! Trà Hoa Trăng hồi sức cho cả nhóm. Hơi trà làm tan màn sương trên cây cầu kế tiếp.',
  'Stay back! I can handle them. Probably.': 'Lùi lại! Mình tự lo được. Chắc vậy.',
  'Nori, you don’t have to do it alone!': 'Nori, bạn đâu cần phải một mình!',
  'Okay. I couldn’t handle them. Thanks, Pip.': 'Được rồi. Mình không lo nổi thật. Cảm ơn nhé, Pip.',
  'Watch my kite, though. It’s the fastest thing on any island.': 'Nhưng xem con diều của mình này. Nó nhanh nhất trên mọi hòn đảo đấy.',
  'Nori joined! Kite Dash calms one Mistling twice as much.': 'Nori đã nhập hội! Diều Lướt vỗ về một Bé Sương mạnh gấp đôi.',
  'Hoo! Visitors on Old Oak Hill. Hazel left the summit path in my care.': 'Hú! Có khách lên Đồi Sồi Già. Bà Hazel giao con đường lên đỉnh cho ta trông coi.',
  'It opens only for those who can answer a riddle.': 'Đường chỉ mở cho ai trả lời được một câu đố.',
  'Round and warm, I wake the night. Five of me make the whole sky bright. What am I?': 'Tròn tròn ấm áp, ta đánh thức màn đêm. Năm chiếc như ta làm cả bầu trời sáng lên. Ta là gì?',
  'A lantern': 'Chiếc đèn lồng',
  'The moon': 'Mặt trăng',
  'A firefly': 'Con đom đóm',
  'Hoo-hoo, not quite. Think of the clearing on Lantern Night…': 'Hú hú, chưa đúng rồi. Nghĩ về bãi cỏ trong Đêm Đèn Lồng xem…',
  'Splendid! A lantern it is. Every story needs someone to write it down, so I’m coming too.': 'Tuyệt lắm! Đúng là chiếc đèn lồng. Câu chuyện nào cũng cần người ghi lại, nên ta đi cùng.',
  'Juniper joined! A Riddle puzzles a Mistling for two turns and shows what it loves.': 'Juniper đã nhập hội! Câu Đố làm một Bé Sương bối rối hai lượt và cho biết nó thích gì.',
  'The Thunder Sulk sits on the hill path. Calm it, and the last waystone will wake.': 'Mây Giông Hờn Dỗi đang ngồi chắn lối lên đồi. Vỗ về nó đi, rồi đèn đá cuối cùng sẽ thức giấc.',
  '…P-Pip? Is that you?': '…P-Pip? Là bạn đó hả?',
  'I came up last night to keep Hazel’s beacon company. Then the big fog sat on it, and it won’t move.': 'Tối qua mình lên đây để ở cạnh ngọn đèn hiệu của bà Hazel. Rồi đám sương to đến ngồi lên nó, và không chịu đi.',
  'You came all this way alone? Bramble, that’s the bravest thing I’ve ever heard.': 'Bạn đi cả quãng đường này một mình sao? Bramble, đó là điều dũng cảm nhất mình từng nghe.',
  'I’m still scared. But I can hold a shield. And… here, a dragon fruit. For courage.': 'Mình vẫn sợ. Nhưng mình cầm khiên được. Và… đây, một quả thanh long. Để thêm can đảm.',
  'Bramble joined! Lantern Shield halves the mist’s chill for two rounds.': 'Bramble đã nhập hội! Khiên Đèn Lồng giảm một nửa cái lạnh của sương trong hai vòng.',
  'Hmmmm… Everyone leaves. The Keeper left. The lights left.': 'Hừmmm… Ai rồi cũng đi. Người Giữ Đèn đã đi. Ánh sáng cũng đi.',
  'We came to light the beacon, so Hazel can find her way home.': 'Tụi mình đến để thắp ngọn đèn hiệu, để bà Hazel tìm được đường về.',
  '…Then you will leave too. Let the summit stay grey.': '…Rồi các ngươi cũng sẽ đi. Cứ để đỉnh núi xám xịt thế này.',
  'Why… are you still here?': 'Sao… các ngươi vẫn còn ở đây?',
  'Because friends stay. And Hazel left notes, for you too.': 'Vì bạn bè thì ở lại. Và bà Hazel cũng để lại thư cho ông nữa.',
  '…Warm. I forgot what warm felt like.': '…Ấm quá. Ta đã quên mất cảm giác ấm áp là thế nào.',
  'Old Fog shimmered gold, and a thousand fireflies rose from the summit.': 'Sương Già ánh lên màu vàng, và hàng nghìn con đom đóm bay lên từ đỉnh núi.',
  'The beacon blazed. Far across the clouds, a single lantern answered.': 'Ngọn đèn hiệu rực sáng. Xa tít bên kia biển mây, một chiếc đèn lồng sáng lên đáp lại.',
  'Pip, I saw it: every light, every friend. I’m on my way. Save me a seat on the blanket. — Grandma Hazel': 'Pip, bà thấy rồi: từng ngọn đèn, từng người bạn. Bà đang trên đường về. Để dành cho bà một chỗ trên tấm khăn nhé. — Bà Hazel',
  'The mist hums a sleepy tune, and everyone dozes off…': 'Sương ngân nga một khúc ru, và cả nhóm thiu thiu ngủ…',
  '…and wakes by the last warm waystone, hearts full again.': '…rồi tỉnh dậy bên đèn đá ấm áp gần nhất, sức lực đã đầy lại.',
  'One of Hazel’s picnic baskets, still packed with fruit.': 'Một chiếc giỏ dã ngoại của bà Hazel, vẫn còn đầy trái cây.',
  'Only crumbs and a checked napkin left.': 'Chỉ còn vụn bánh và một chiếc khăn ăn kẻ ô.',
  'Old Fog is curled around the beacon. Maybe a friend nearby knows what happened.': 'Sương Già cuộn tròn quanh ngọn đèn hiệu. Có lẽ một người bạn gần đây biết chuyện gì đã xảy ra.',
  'Hazel’s beacon is shining. The whole trail glows behind you.': 'Đèn hiệu của bà Hazel đang tỏa sáng. Cả con đường phía sau bạn đều lấp lánh.',
  // ---------------------------------------------------------------- Hazel's notes
  'Pip, if you’re reading this, you found the trail. The mist isn’t wicked, only lonely. Be kind to it. — H.': 'Pip, nếu con đang đọc thư này thì con đã tìm ra con đường rồi. Sương không xấu đâu, chỉ cô đơn thôi. Hãy tử tế với nó nhé. — H.',
  'Momo’s moonflowers grow on Fernhollow too. Tea is just warmth you can hold in your paws. — H.': 'Hoa trăng của Momo cũng mọc ở Fernhollow. Trà chỉ là chút hơi ấm con có thể nâng trong tay. — H.',
  'Nori, I never once blamed you for the lantern string. Lights go out. Friends light them again. — H.': 'Nori, bà chưa bao giờ trách con chuyện sợi dây đèn. Đèn có lúc tắt. Bạn bè sẽ thắp lại. — H.',
  'Juniper keeps my riddles. Here’s one more: what grows bigger the more you share it? — H.': 'Juniper giữ các câu đố của bà. Thêm một câu nữa nhé: thứ gì càng chia sẻ càng lớn thêm? — H.',
  'Old Fog has kept this beacon company since I left. Please tell it I said thank you. — H.': 'Từ ngày bà đi, Sương Già vẫn ở bên ngọn đèn hiệu này. Hãy nói với nó rằng bà cảm ơn nhé. — H.',
  // ---------------------------------------------------------------- names and places
  'Grandma Hazel': 'Bà Hazel',
  'Old Fog': 'Sương Già',
  'Signpost': 'Biển chỉ đường',
  'Landing Meadow': 'Đồng Cỏ Đáp Chân',
  'Lily Pond Glade': 'Trảng Hồ Sen',
  'Toadstool Wood': 'Rừng Nấm',
  'Old Oak Hill': 'Đồi Sồi Già',
  'Beacon Summit': 'Đỉnh Đèn Hiệu',
  'Weepy Wisp': 'Sương Mít Ướt',
  'Grumbly Puff': 'Mây Cau Có',
  'Shy Flicker': 'Đốm Sương Nhút Nhát',
  'Thunder Sulk': 'Mây Giông Hờn Dỗi',
  // ---------------------------------------------------------------- fruit, specials, likes
  'Cherries': 'Anh đào',
  'Restores 12 heart to one friend.': 'Hồi 12 tim cho một bạn.',
  'Strawberry': 'Dâu tây',
  'Restores 22 heart to one friend.': 'Hồi 22 tim cho một bạn.',
  'Lemon': 'Chanh vàng',
  'Wakes a sleepy friend with half their heart.': 'Đánh thức một bạn đang ngủ gật với nửa số tim.',
  'Peach': 'Đào',
  'Restores 45 heart to one friend.': 'Hồi 45 tim cho một bạn.',
  'Watermelon': 'Dưa hấu',
  'Everyone shares: 18 heart each.': 'Cả nhóm cùng ăn: mỗi bạn hồi 18 tim.',
  'Dragon fruit': 'Thanh long',
  'Wakes everyone and fills every heart.': 'Đánh thức mọi người và hồi đầy tim cho tất cả.',
  'Lantern Glow': 'Ánh Đèn Lồng',
  'Warm light calms every Mistling a little.': 'Ánh sáng ấm áp vỗ về mọi Bé Sương một chút.',
  'Moonflower Tea': 'Trà Hoa Trăng',
  'Heals every friend and wakes sleepy ones.': 'Hồi sức cho cả nhóm và đánh thức các bạn đang ngủ gật.',
  'Kite Dash': 'Diều Lướt',
  'A big swoop: twice the calm for one Mistling.': 'Một cú lướt thật lớn: vỗ về một Bé Sương gấp đôi.',
  'Riddle': 'Câu Đố',
  'Puzzles a Mistling for two turns and shows what it loves.': 'Làm một Bé Sương bối rối hai lượt và cho biết nó thích gì.',
  'Lantern Shield': 'Khiên Đèn Lồng',
  'The mist’s chill is halved for two rounds.': 'Cái lạnh của sương giảm một nửa trong hai vòng.',
  'Hazel’s notes': 'Thư của bà Hazel',
  'Read Hazel’s notes aloud. Each one you found calms Old Fog.': 'Đọc to những lá thư của bà Hazel. Mỗi lá thư bạn tìm được sẽ vỗ về Sương Già.',
  'Loves hugs': 'Thích được ôm',
  'Loves lantern light': 'Thích ánh đèn lồng',
  'Loves kites': 'Thích diều',
  'Loves riddles': 'Thích câu đố',
  // ---------------------------------------------------------------- goals
  'The trail is lit. Hazel is on her way.': 'Con đường đã sáng. Bà Hazel đang trên đường về.',
  'Light the waystone by the bridge.': 'Thắp đèn đá cạnh cây cầu.',
  'Calm the Mistling in the meadow.': 'Vỗ về Bé Sương trên đồng cỏ.',
  'Cross the bridge and find Momo.': 'Qua cầu và tìm Momo.',
  'Follow the steam to Toadstool Wood and find Nori.': 'Theo làn hơi trà đến Rừng Nấm và tìm Nori.',
  'Light the waystone in the wood.': 'Thắp đèn đá trong rừng.',
  'Climb Old Oak Hill and answer Juniper’s riddle.': 'Leo lên Đồi Sồi Già và giải câu đố của Juniper.',
  'Light the waystone on Old Oak Hill.': 'Thắp đèn đá trên Đồi Sồi Già.',
  'Calm the Thunder Sulk on the hill.': 'Vỗ về Mây Giông Hờn Dỗi trên đồi.',
  'Climb to the summit. Someone is hiding there.': 'Leo lên đỉnh. Có ai đó đang trốn ở đó.',
  'Calm Old Fog and light Hazel’s beacon.': 'Vỗ về Sương Già và thắp đèn hiệu của bà Hazel.',
  // ---------------------------------------------------------------- play
  'The trail could not load. Please check your connection and reload.': 'Không tải được con đường. Hãy kiểm tra kết nối rồi tải lại trang.',
  'Drag on the left to walk, or tap where to go.': 'Kéo ở nửa trái để đi, hoặc chạm vào nơi muốn đến.',
  'Walk with WASD or the arrow keys. E or Space talks.': 'Đi bằng WASD hoặc phím mũi tên. E hoặc Space để nói chuyện.',
  'Lv {n}': 'Cấp {n}',
  'Start the trail over': 'Đi lại từ đầu',
  'Tap again to start over': 'Chạm lần nữa để bắt đầu lại',
  'Read': 'Đọc',
  'Look': 'Xem',
  'Open': 'Mở',
  'Rest': 'Nghỉ',
  'Light': 'Thắp',
  'Talk': 'Nói',
  'Hazel’s note {n} of 5': 'Thư của bà Hazel: {n}/5',
  'Everyone rests by the waystone. Hearts are full and the trail is saved.': 'Cả nhóm nghỉ bên đèn đá. Tim đã đầy và hành trình đã được lưu.',
  'Choose Hug, then tap the Mistling.': 'Chọn Ôm, rồi chạm vào Bé Sương.',
  'sleepy': 'ngủ gật',
  'in {n}': 'còn {n}',
  '{name}’s turn': 'Lượt của {name}',
  'Hug': 'Ôm',
  'Fruit': 'Trái cây',
  'Guard': 'Chụm lại',
  'A warm hug calms one Mistling.': 'Một cái ôm ấm áp vỗ về một Bé Sương.',
  'Share fruit from the basket.': 'Chia trái cây trong giỏ.',
  'Brace together: half the chill this round.': 'Chụm lại với nhau: nửa cái lạnh trong vòng này.',
  'ready in {n}': 'chờ {n} lượt',
  'Tap a Mistling.': 'Chạm vào một Bé Sương.',
  'Pick a Mistling: arrows, then Enter. Or click one.': 'Chọn Bé Sương: phím mũi tên rồi Enter. Hoặc bấm vào nó.',
  'Nobody needs that right now.': 'Lúc này chưa ai cần món đó.',
  'Who gets the {fruit}? Tap a friend’s card.': 'Ai sẽ ăn {fruit}? Chạm vào thẻ của một bạn.',
  'Tap (or press Space) as the rings meet for a Lovely hug!': 'Chạm (hoặc nhấn Space) khi hai vòng gặp nhau để có cái ôm Tuyệt vời!',
  'Lovely!': 'Tuyệt vời!',
  'It loves that!': 'Nó thích lắm!',
  'It’s hiding!': 'Nó trốn mất rồi!',
  'Puzzled!': 'Bối rối!',
  'Awake!': 'Tỉnh rồi!',
  'Lantern Shield!': 'Khiên Đèn Lồng!',
  'Braced': 'Đã chụm lại',
  'Hazel’s notes ×{n}': 'Thư của bà ×{n}',
  'The mist stirs…': 'Sương đang cựa quậy…',
  'Still puzzled…': 'Vẫn còn bối rối…',
  'Sulking…': 'Đang hờn dỗi…',
  'Hides in the fog!': 'Trốn vào màn sương!',
  'Gathers its fog!': 'Gom sương lại!',
  'Tap (or press Space) as the mist reaches you to brace!': 'Chạm (hoặc nhấn Space) khi sương chạm tới để chống đỡ!',
  'Brave!': 'Dũng cảm!',
  'Sleepy…': 'Buồn ngủ…',
  '+{n} glow': '+{n} ánh sáng',
  'Level {n}! Hearts and hugs grow stronger.': 'Lên cấp {n}! Tim và những cái ôm đều mạnh hơn.',
  'What teamwork!': 'Đồng đội tuyệt vời!',
  'Friends found': 'Bạn đã tìm thấy',
  'Lovely moments': 'Khoảnh khắc tuyệt vời',
  'Minutes on the trail': 'Số phút trên đường',
  'Use': 'Dùng',
  'The basket is empty. Hazel hid picnic baskets on every islet.': 'Giỏ trống rồi. Bà Hazel giấu giỏ dã ngoại trên mỗi hòn đảo nhỏ.',
  'Heart {h}/{max} · Warmth {w}': 'Tim {h}/{max} · Ấm áp {w}',
  'Level {n} · {g} glow': 'Cấp {n} · {g} ánh sáng',
  'No notes yet. Hazel tucked five of them along the trail.': 'Chưa có thư nào. Bà Hazel đã giấu năm lá thư dọc đường.',
  'Everyone is already full of heart.': 'Mọi người đều đã đầy tim.',
  '{name} shared the {fruit}.': '{name} đã ăn {fruit}.',
  // ---------------------------------------------------------------- page
  'Sound': 'Âm thanh',
  'Menu': 'Trình đơn',
  'Skip scene': 'Bỏ qua cảnh',
  'Back': 'Quay lại',
  'A LITTLE ADVENTURE FROM THE LANTERN PICNIC': 'MỘT CHUYẾN PHIÊU LƯU NHỎ TỪ BUỔI DÃ NGOẠI ĐÈN LỒNG',
  'The Lantern Trail': 'Con Đường Đèn Lồng',
  'Five friends scattered by the mist. Five islets in the sky. One beacon to light Hazel home.': 'Năm người bạn bị sương thổi tản mát. Năm hòn đảo nhỏ trên trời. Một ngọn đèn hiệu soi đường bà Hazel về nhà.',
  'Begin the trail': 'Bắt đầu hành trình',
  'Start a new trail': 'Bắt đầu hành trình mới',
  'Continue the trail': 'Tiếp tục hành trình',
  'Back to the picnic': 'Về buổi dã ngoại',
  'Language': 'Ngôn ngữ',
  'About 15 minutes · plays with touch, mouse, keyboard or a gamepad': 'Khoảng 15 phút · chơi bằng cảm ứng, chuột, bàn phím hoặc tay cầm',
  'THE LANTERN TRAIL': 'CON ĐƯỜNG ĐÈN LỒNG',
  'Hazel is on her way home.': 'Bà Hazel đang trên đường về nhà.',
  'Every waystone is lit, and the beacon on the summit shines across the clouds.': 'Mọi đèn đá đều đã sáng, và ngọn đèn hiệu trên đỉnh tỏa sáng khắp biển mây.',
  'Keep wandering Fernhollow': 'Dạo tiếp Fernhollow',
  'FERNHOLLOW': 'FERNHOLLOW',
  'Your trail': 'Hành trình của bạn',
  'Close': 'Đóng',
  'Basket': 'Giỏ',
  'Friends': 'Bạn bè',
  'Notes': 'Thư',
  'Settings': 'Cài đặt',
  'Timing help': 'Hỗ trợ canh nhịp',
  'Wider windows for Lovely hugs and Brave braces.': 'Nới rộng thời điểm cho cái ôm Tuyệt vời và cú chống đỡ Dũng cảm.',
  'Calm motion': 'Chuyển động êm dịu',
  'Less shaking, bobbing and sparkle.': 'Bớt rung lắc, nhấp nhô và lấp lánh.',
  'Keys: WASD or arrows walk · E or Space talks and taps · 1–4 pick in battle · Esc menu': 'Phím: WASD hoặc mũi tên để đi · E hoặc Space để nói và chạm · 1–4 để chọn khi vỗ về · Esc mở trình đơn',
  'Unrolling Hazel’s map…': 'Đang mở bản đồ của bà Hazel…',
  'Try again': 'Thử lại',
};
