import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {mkdir} from 'node:fs/promises';
import {newPicnic,PICNIC_SAVE_KEY} from '../src/picnic-game.js';
await mkdir('artifacts',{recursive:true});
const browser=await chromium.launch({channel:'chrome',headless:true});
const ctx=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1});
const page=await ctx.newPage(),errors=[];
page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(`${r.status()} ${r.url()}`);});
const state=()=>page.evaluate(()=>window.__picnic.getState());
async function ready(p=page){await p.waitForFunction(()=>window.__picnic);await p.waitForFunction(()=>getComputedStyle(document.getElementById('loading')).opacity==='0');}
async function point(p,position,height=.6){return p.evaluate(({position,height})=>{const pt=window.__picnic.project(position,height),r=document.querySelector('canvas').getBoundingClientRect();return{x:pt.x+r.x,y:pt.y+r.y};},{position,height});}
async function drag(from,to,{fromHeight=.6,toHeight=.6,preview=false}={}){const a=await point(page,from,fromHeight),b=await point(page,to,toHeight);await page.mouse.move(a.x,a.y);await page.mouse.down();await page.mouse.move(b.x,b.y,{steps:15});if(preview)assert.equal(await page.locator('#merge-preview').isVisible(),true);await page.mouse.up();await page.waitForFunction(()=>!window.__picnic.getSelection());}
try{
 await page.goto('http://localhost:4173/classic.html?mode=free&debug');await ready();await page.screenshot({path:'artifacts/picnic-desktop.png'});
 let s=await state(),pair=s.fruits.filter(f=>f.level===0);await drag(pair[0],pair[1],{preview:true});s=await state();assert.equal(s.merges,1);assert.equal(s.score,20);assert.equal(s.fruits.length,11);console.log('PASS: direct mouse drag, matching preview, merge and reward');
 await page.locator('#undo').click();s=await state();assert.equal(s.fruits.length,12);assert.equal(s.score,0);assert.equal(s.merges,0);console.log('PASS: undo restores both fruits and reward');
 const cancelPoint=await point(page,s.fruits[0]);await page.mouse.move(cancelPoint.x,cancelPoint.y);await page.mouse.down();await page.mouse.move(cancelPoint.x+80,cancelPoint.y+70,{steps:8});await page.keyboard.press('Escape');await page.mouse.up();assert.deepEqual((await state()).fruits,s.fruits);console.log('PASS: cancelling a drag preserves the fruit and board');
 pair=s.fruits.filter(f=>f.level===5);const mergeId=s.nextId;await drag(pair[0],pair[1]);s=await state();assert.ok(s.discovered.includes(10));assert.equal(s.fruits.find(f=>f.level===10)?.id,mergeId);await page.screenshot({path:'artifacts/picnic-discovery.png'});console.log('PASS: higher fruit discovery happens on the play surface');
 const fruit=s.fruits.find(f=>f.level===3);await drag(fruit,{x:.73,y:.87},{toHeight:.4,preview:true});s=await state();assert.equal(s.shared,1);assert.equal(s.kindness,5);assert.equal(s.fruits.length,10);console.log('PASS: direct sharing with Pip and visible kindness progression');
 const count=s.fruits.length;const basket=await page.locator('#basket-label').boundingBox();const dest=await point(page,{x:.4,y:.37},.1);await page.mouse.move(basket.x+basket.width/2,basket.y+basket.height/2);await page.mouse.down();await page.mouse.move(dest.x,dest.y,{steps:12});await page.mouse.up();s=await state();assert.equal(s.fruits.length,count+1);assert.equal(s.supplyIndex,1);console.log('PASS: dragging a fresh fruit out of the supply basket');
 const a=s.fruits.find(f=>f.level===0),b=s.fruits.find(f=>f.level===4),before=s.fruits.length;await drag(a,b);assert.equal((await state()).fruits.length,before);console.log('PASS: mismatched fruit stays intact');
 s=await state();const moved=s.fruits.find(f=>f.level===1);await drag(moved,{x:.52,y:.42});assert.equal((await state()).fruits.length,before);console.log('PASS: free placement on the surface');
 const pip=(await state()).pip;await drag(pip,{x:.55,y:.83},{fromHeight:1.0,toHeight:1.0});assert.ok(Math.abs((await state()).pip.x-pip.x)>.1);console.log('PASS: doll itself can be picked up and moved');
 const saved=await state();await page.reload();await ready();s=await state();assert.deepEqual(s.fruits,saved.fruits);assert.equal(s.score,saved.score);assert.deepEqual(s.pip,saved.pip);console.log('PASS: fruit layout, rewards and doll position survive reload');
 await page.locator('#picnic').focus();await page.keyboard.press('n');assert.ok(await page.evaluate(()=>window.__picnic.getSelection()));await page.keyboard.press('ArrowRight');await page.keyboard.press('Enter');await page.keyboard.press('b');assert.equal((await state()).supplyIndex,2);await page.keyboard.press('u');assert.equal((await state()).supplyIndex,1);console.log('PASS: keyboard picking, moving, placing, supply and undo');
 await page.locator('#help').click();await page.locator('#quiet-motion').check();await page.locator('#back-to-play').click();assert.equal((await state()).reducedMotion,true);await page.locator('#sound').click();assert.equal((await state()).sound,true);await page.locator('#sound').click();console.log('PASS: optional help, quiet motion and sound');
 const downloadPromise=page.waitForEvent('download');await page.locator('#photo').click();await(await downloadPromise).saveAs('artifacts/picnic-photo.png');
 const mobile=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,isMobile:true,hasTouch:true});const phone=await mobile.newPage();phone.on('pageerror',e=>errors.push(e.message));await phone.goto('http://localhost:4173/classic.html?mode=free&debug');await ready(phone);await phone.screenshot({path:'artifacts/picnic-mobile.png'});
 const cdp=await mobile.newCDPSession(phone);let fruits=await phone.evaluate(()=>window.__picnic.getState().fruits.filter(f=>f.level===0));const p1=await point(phone,fruits[0]),p2=await point(phone,fruits[1]);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:p1.x,y:p1.y}]});for(let i=1;i<=10;i++)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:p1.x+(p2.x-p1.x)*i/10,y:p1.y+(p2.y-p1.y)*i/10}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await phone.evaluate(()=>window.__picnic.getState().merges),1);console.log('PASS: actual emulated touch drag merges fruit');
 fruits=await phone.evaluate(()=>window.__picnic.getState().fruits.filter(f=>f.level===3));const t1=await point(phone,fruits[0]),t2=await point(phone,fruits[1]);await phone.touchscreen.tap(t1.x,t1.y);assert.ok(await phone.evaluate(()=>window.__picnic.getSelection()));await phone.touchscreen.tap(t2.x,t2.y);assert.equal(await phone.evaluate(()=>window.__picnic.getState().merges),2);console.log('PASS: tap-to-pick and tap-to-place alternative');
 const phoneState=await phone.evaluate(()=>window.__picnic.getState());await phone.reload();await ready(phone);assert.deepEqual(await phone.evaluate(()=>window.__picnic.getState().fruits),phoneState.fruits);console.log('PASS: portrait save preserves the exact fruit layout');
 await phone.setViewportSize({width:360,height:640});assert.equal(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await phone.screenshot({path:'artifacts/picnic-small-mobile.png'});await mobile.close();
 // A late-game fixture in an isolated test context verifies the final gesture and its art.
 const finalState=newPicnic();finalState.fruits=[{id:1,level:11,x:.3,y:.4},{id:2,level:11,x:.6,y:.4}];finalState.nextId=3;finalState.kindness=14;finalState.discovered=[0,1,2,3,4,5,6,7];
 const finalContext=await browser.newContext({viewport:{width:1440,height:1000}});await finalContext.addInitScript(({key,value})=>localStorage.setItem(key,value),{key:PICNIC_SAVE_KEY,value:JSON.stringify(finalState)});const finale=await finalContext.newPage();finale.on('pageerror',e=>errors.push(e.message));await finale.goto('http://localhost:4173/classic.html?mode=free&debug');await ready(finale);
 const fa=await point(finale,finalState.fruits[0]),fb=await point(finale,finalState.fruits[1]);await finale.mouse.move(fa.x,fa.y);await finale.mouse.down();await finale.mouse.move(fb.x,fb.y,{steps:12});await finale.mouse.up();assert.equal(await finale.evaluate(()=>window.__picnic.getState().fruits[0].level),8);await finale.screenshot({path:'artifacts/picnic-watermelon.png'});
 const watermelon=await finale.evaluate(()=>window.__picnic.getState().fruits[0]);const start=await point(finale,watermelon,.75),end=await point(finale,{x:.73,y:.87},.5);await finale.mouse.move(start.x,start.y);await finale.mouse.down();await finale.mouse.move(end.x,end.y,{steps:15});await finale.mouse.up();assert.equal(await finale.evaluate(()=>window.__picnic.getState().picnics),1);assert.equal(await finale.evaluate(()=>window.__picnic.getState().score),280);await finalContext.close();console.log('PASS: dragon fruit merge, watermelon discovery and picnic finale');
 assert.deepEqual(errors,[]);console.log('PASS: small mobile layout and no browser errors');
}catch(error){await page.screenshot({path:'artifacts/picnic-failure.png'});console.error('STATE',await state().catch(()=>null));throw error;}finally{await browser.close();}
