import test from 'node:test';
import assert from 'node:assert/strict';
import {newPicnic,loadPicnic,PICNIC_ITEMS,FRUITS,PLATE,MAX_FRUITS,allItems,itemInfo,distance,introduceBubbles,addBubble,addFruit,dropFruit,mergePlan,additionMergePlan} from '../src/picnic-game.js';
const frame={width:14,depth:9.8};
function fixture(level=0,count=2,dimensions=frame){const s=newPicnic();s.fruits=[];s.bubbleWelcome=true;s.nextId=count+1;s.picnicItems=[{id:1,kind:'picnic',level,x:.12,y:.15}];const center={x:.5,y:.4},radius=PICNIC_ITEMS[level].radius*2+.08;for(let i=0;i<count-1;i++){const a=i*Math.PI*2/(count-1);s.picnicItems.push({id:i+2,kind:'picnic',level,x:center.x+Math.cos(a)*radius/dimensions.width,y:center.y+Math.sin(a)*radius/dimensions.depth});}return{s,center};}
test('every bubble and picnic tier merges with exact 2/3/4 rewards on both mat shapes',()=>{for(const dimensions of [frame,{width:7.4,depth:11.8},{width:14,depth:6.4}])for(let level=0;level<PICNIC_ITEMS.length-1;level++)for(const count of [2,3,4]){const{s,center}=fixture(level,count,dimensions),before=structuredClone(s),plan=mergePlan(s,1,center,dimensions);assert.deepEqual(s,before);assert.equal(plan.kind,'picnic');assert.equal(plan.count,count);const result=dropFruit(s,1,center,dimensions);assert.equal(result.type,'merge');assert.equal(result.reward,(level+2)*10*(count-1));assert.equal(s.picnicItems.length,1);assert.equal(s.picnicItems[0].level,level+1);assert.ok(s.picnicDiscovered.includes(level+1));assert.equal(s.discovered.length,6);const after=structuredClone(s);assert.equal(dropFruit(s,1,center,dimensions).ok,false);assert.deepEqual(s,after);}});
test('fruit and bubbles never cross-merge, and distant bubble chains do not join',()=>{const{s,center}=fixture(0,3);s.fruits=[{id:4,level:0,...center}];s.picnicItems.push({id:5,kind:'picnic',level:0,x:center.x+1.25/frame.width,y:center.y});s.nextId=6;assert.deepEqual(new Set(mergePlan(s,1,center,frame).removed),new Set([1,2,3]));dropFruit(s,1,center,frame);assert.equal(s.fruits.length,1);assert.ok(s.picnicItems.some(f=>f.id===5));const mixed=fixture().s;mixed.picnicItems.splice(1);mixed.fruits=[{id:2,level:0,x:.6,y:.4}];assert.equal(dropFruit(mixed,1,mixed.fruits[0],frame).type,'move');assert.equal(mixed.score,0);assert.ok(distance(mixed.picnicItems[0],mixed.fruits[0],frame)>=PICNIC_ITEMS[0].radius+FRUITS[0].radius);});
test('bubble jar creates only small bubbles and can complete a previewed group',()=>{const{s,center}=fixture(0,3);s.picnicItems.shift();const before=structuredClone(s),plan=additionMergePlan(s,center,frame,'picnic');assert.equal(plan.count,3);assert.deepEqual(s,before);const result=addBubble(s,center,frame,{merge:true});assert.equal(result.count,3);assert.equal(result.reward,40);assert.equal(s.supplyIndex,0);assert.equal(addBubble(s,{x:.15,y:.6},frame).fruit.level,0);assert.deepEqual(loadPicnic(JSON.stringify(s)).picnicItems,s.picnicItems);});
test('bubble introduction preserves old saves and respects the shared board capacity',()=>{const old=newPicnic();delete old.picnicItems;delete old.picnicDiscovered;delete old.bubbleWelcome;old.score=450;const s=loadPicnic(JSON.stringify(old)),fruits=structuredClone(s.fruits);introduceBubbles(s,frame);assert.equal(s.picnicItems.length,2);assert.equal(s.score,450);assert.deepEqual(s.fruits,fruits);const before=structuredClone(s);introduceBubbles(s,frame);assert.deepEqual(s,before);while(allItems(s).length<MAX_FRUITS)assert.equal(addBubble(s,{x:.5,y:.5},frame).ok,true);const full=structuredClone(s);assert.equal(addBubble(s).ok,false);assert.equal(addFruit(s).ok,false);assert.deepEqual(s,full);});
test('maximum picnic hampers stay separate and sharing celebrates only once',()=>{const{s}=fixture(5);assert.equal(dropFruit(s,1,s.picnicItems[1],frame).type,'move');assert.equal(s.picnicItems.length,2);const result=dropFruit(s,1,PLATE,frame);assert.equal(result.hamper,true);assert.equal(result.feast,false);assert.equal(result.reward,110);assert.equal(s.picnics,1);const before=structuredClone(s);assert.equal(dropFruit(s,1,PLATE).ok,false);assert.deepEqual(s,before);});
test('malformed picnic saves cannot duplicate identities or create invalid toys',()=>{const s=newPicnic();s.picnicItems=[{id:1,level:0,x:.4,y:.4},{id:15,level:99,x:.4,y:.4},{id:16,level:2,x:99,y:-8},{id:16,level:3,x:.5,y:.5}];s.picnicDiscovered=[-1,0,99,3];const loaded=loadPicnic(JSON.stringify(s));assert.equal(loaded.picnicItems.length,1);assert.equal(loaded.picnicItems[0].kind,'picnic');assert.ok(loaded.picnicItems[0].x<1);assert.equal(loaded.nextId,17);assert.deepEqual(loaded.picnicDiscovered,[0,2,3]);assert.ok(itemInfo(loaded.picnicItems[0]));});
