// Vietnamese presentation copy. English source strings are stable fallback keys.
export const VI = {
  "Grandma Hazel": "Bà Hazel",
  "A LETTER, TUCKED IN THE PICNIC BASKET": "LÁ THƯ NẰM TRONG GIỎ DÃ NGOẠI",
  "Dear Pip,": "Pip yêu quý,",
  "The lanterns of the clearing have been dark for too long. On Lantern Night, spread the blanket, fill the basket, and light them again: one lantern for every friend who finds their way to you.": "Những chiếc đèn ở bãi cỏ đã tắt quá lâu rồi. Vào Đêm Đèn Lồng, con hãy trải khăn, xếp đầy giỏ và thắp sáng chúng lần nữa: mỗi người bạn ghé thăm sẽ có một chiếc đèn.",
  "I’ve gone to light the far islands. Five lanterns shine bright enough to see from anywhere in the sky. I’ll be watching for them.": "Bà đi thắp sáng những hòn đảo xa. Năm chiếc đèn đủ sáng để nhìn thấy từ bất cứ đâu trên bầu trời. Bà sẽ ngóng ánh đèn của con.",
  "P.S. Two little things make one bigger thing. That’s the whole secret.": "Tái bút: Hai thứ nhỏ ghép lại thành một thứ lớn hơn. Bí quyết chỉ có vậy thôi.",
  "With all my love, Grandma Hazel": "Thương con thật nhiều, Bà Hazel",
  "Spread the blanket": "Trải khăn dã ngoại",
  "A LETTER, CARRIED HOME BY A SKY LANTERN": "LÁ THƯ THEO ĐÈN TRỜI VỀ NHÀ",
  "I saw them. Every one. From the farthest island in the sky, your five lanterns were the brightest thing I have ever seen.": "Bà thấy rồi. Đủ cả năm chiếc. Từ hòn đảo xa nhất trên trời, năm chiếc đèn của con là ánh sáng rực rỡ nhất bà từng thấy.",
  "Keep the blanket spread and the basket full. I’m coming home for the next Lantern Night, and I’m bringing new friends.": "Cứ để khăn trải rộng và giỏ đầy nhé. Đêm Đèn Lồng tới bà sẽ về nhà, mang theo cả những người bạn mới.",
  "All my love, Grandma Hazel": "Yêu con, Bà Hazel",
  "Stay for the lanterns": "Ở lại ngắm đèn",
  "The Firefly Clearing": "Bãi cỏ đom đóm",
  "The clearing’s been so quiet since Grandma Hazel went away.": "Từ ngày bà Hazel đi, bãi cỏ yên ắng quá.",
  "Her letter says the first lantern is for whoever starts. So… that’s me.": "Bà viết rằng chiếc đèn đầu tiên dành cho người bắt đầu. Vậy… là mình rồi.",
  "A berry welcome and a cherry skewer, just like she used to make. Here goes!": "Dâu tây đón khách và một xiên anh đào, y như bà từng làm. Bắt đầu nào!",
  "Two little things make one bigger thing. She was right!": "Hai thứ nhỏ thành một thứ lớn hơn. Bà nói đúng thật!",
  "Mm. Tastes like summer.": "Ưm. Hương vị mùa hè đây rồi.",
  "One more and it’s a proper welcome.": "Thêm một chút nữa là đủ món đón khách rồi.",
  "Three cherries, one skewer. Grandma’s favourite.": "Ba quả anh đào, một chiếc xiên. Món bà thích nhất.",
  "Whoa, it just kept going!": "Ồ, cứ ghép tiếp mãi luôn!",
  "A little extra for the table.": "Thêm chút quà cho cả bàn.",
  "It’s lit! Grandma, look, the first lantern!": "Sáng rồi! Bà ơi, nhìn này, chiếc đèn đầu tiên!",
  "…Did something just rustle down by the path?": "…Có tiếng gì xào xạc dưới lối đi phải không?",
  "The first lantern is lit.": "Chiếc đèn đầu tiên đã sáng.",
  "Pip’s little light is shining. Down the hill, a traveller has stopped to look.": "Ánh đèn nhỏ của Pip đang tỏa sáng. Dưới chân đồi, một vị khách dừng bước ngắm nhìn.",
  "Pip lit the first lantern alone, and it was enough. Somewhere down the hill, a traveller stopped, and turned toward the light.": "Pip tự thắp chiếc đèn đầu tiên, thế là đủ. Đâu đó dưới chân đồi, một vị khách dừng lại và đi về phía ánh sáng.",
  "Berry welcome: two strawberries, a skewer of cherries, and someone brave enough to start.": "Món dâu đón khách: hai quả dâu tây, một xiên anh đào và một người đủ can đảm để bắt đầu.",
  "The Path of Stepping Stones": "Lối đi lát đá",
  "Excuse me… I followed your light. I’ve been hopping between islands for three whole days.": "Xin lỗi… mình đi theo ánh đèn. Mình đã nhảy từ đảo này sang đảo khác suốt ba ngày rồi.",
  "Three days? You must be starving. Sit, sit!": "Ba ngày sao? Chắc bạn đói lắm rồi. Ngồi xuống đi!",
  "Is there… room for one more? I don’t want to be any bother.": "Còn… chỗ cho mình không? Mình không muốn làm phiền đâu.",
  "Grandma says a picnic isn’t finished until someone new sits down.": "Bà bảo buổi dã ngoại chỉ trọn vẹn khi có thêm một người bạn mới ngồi cùng.",
  "Oh! And… might I have one pear? For the tea. Only if it’s no trouble.": "À! Mình… xin thêm một quả lê được không? Để uống cùng trà. Nếu không phiền nhé.",
  "A pear! How did you know? That’s exactly what I was too shy to ask for.": "Một quả lê! Sao bạn biết hay vậy? Mình ngại nên chưa dám xin đấy.",
  "Oh, clever! We never did it like that back home.": "Ôi, khéo thật! Ở quê mình chưa từng làm như vậy.",
  "Oranges taste like the sunsets on my old island.": "Vị cam làm mình nhớ hoàng hôn trên hòn đảo cũ.",
  "Thank you. Truly.": "Cảm ơn bạn. Thật lòng đấy.",
  "Apples on a stick! I haven’t had those since I was little.": "Táo xiên que! Từ hồi bé mình chưa được ăn lại món này.",
  "Goodness! Is it always this lively here?": "Ôi chao! Ở đây lúc nào cũng vui thế này sao?",
  "Oh, for the table? How generous.": "Ồ, cho cả bàn à? Bạn tốt bụng quá.",
  "I brought moonflower tea from home. I was saving it for a special day.": "Mình mang trà hoa trăng từ quê đến. Mình để dành cho một ngày đặc biệt.",
  "I think today might be it.": "Mình nghĩ ngày đó là hôm nay.",
  "Stay as long as you like, Momo. This can be home too.": "Momo, cứ ở lại bao lâu tùy thích. Đây cũng có thể là nhà của bạn.",
  "In the ferns at the edge of the clearing, a pair of amber eyes had been watching all afternoon.": "Trong bụi dương xỉ bên bãi cỏ, một đôi mắt màu hổ phách đã dõi theo suốt buổi chiều.",
  "There’s always room for one more.": "Luôn có chỗ cho một người bạn nữa.",
  "Momo poured moonflower tea for everyone. The sun is turning gold.": "Momo rót trà hoa trăng cho mọi người. Nắng đã chuyển màu vàng óng.",
  "Momo left home looking for somewhere to belong, and found it by the second lantern, over a pot of moonflower tea.": "Momo rời nhà tìm một nơi để gắn bó, rồi tìm thấy bên chiếc đèn thứ hai và ấm trà hoa trăng.",
  "Taste of sunshine: two oranges, one pear for the tea, and a seat saved for someone new.": "Hương vị nắng: hai quả cam, một quả lê uống cùng trà và chỗ ngồi dành cho bạn mới.",
  "The Lantern Posts": "Những cột đèn lồng",
  "Hmph. The clearing used to be so quiet. Look at it now.": "Hừm. Bãi cỏ trước đây yên tĩnh lắm. Giờ thì nhìn xem.",
  "Nori! You’ve been in those ferns since lunch. Come and sit.": "Nori! Bạn ở trong bụi dương xỉ từ trưa rồi. Ra ngồi cùng đi.",
  "I was… guarding them. From ferns.": "Mình đang… canh gác. Đề phòng dương xỉ.",
  "Fine. One watermelon. The biggest one you can make. Then I’ll go.": "Được thôi. Một quả dưa hấu. Quả to nhất bạn làm được. Ăn xong mình đi ngay.",
  "Not bad. For a bear.": "Không tệ. Đối với một chú gấu.",
  "…It’s perfect. Don’t tell anyone I said that.": "…Ngon tuyệt. Đừng kể ai là mình nói thế nhé.",
  "Peaches. Hazel used to put peaches on everything.": "Đào. Bà Hazel hay thêm đào vào mọi món.",
  "Okay, THAT was impressive.": "Được rồi, lần này thì ấn tượng thật đấy.",
  "Sharing, huh? Suit yourself.": "Chia sẻ à? Tùy bạn thôi.",
  "Pip… after this, there’s something I need to tell you.": "Pip… lát nữa mình có chuyện cần nói với bạn.",
  "Pip. The night the lanterns went dark… that was me.": "Pip. Đêm đèn lồng tắt hết… là do mình.",
  "I only wanted to borrow one. I tugged the string, it snapped, and every light went out.": "Mình chỉ muốn mượn một chiếc thôi. Mình kéo dây, dây đứt, rồi tất cả đèn đều tắt.",
  "I’ve been sewing bunting ever since. I thought if I made it pretty enough, I could make it right.": "Từ đó mình cứ may cờ trang trí. Mình nghĩ nếu làm thật đẹp thì có thể sửa được lỗi ấy.",
  "Nori… Grandma never blamed anybody. She said the lanterns were only resting.": "Nori… bà chưa bao giờ trách ai cả. Bà bảo những chiếc đèn chỉ đang nghỉ ngơi thôi.",
  "Will you hang it with us?": "Bạn cùng treo với tụi mình nhé?",
  "…Yeah. Okay.": "…Ừ. Được thôi.",
  "The path turns gold.": "Lối đi ngập ánh vàng.",
  "Nori strung paper bunting between the posts. Some knots are easier to untie together.": "Nori treo dây cờ giấy giữa các cột đèn. Có những nút thắt dễ gỡ hơn khi có bạn cùng làm.",
  "Nori carried a snapped lantern string and a secret for a whole year. At sunset, Nori set both down and hung the bunting where everyone could see it.": "Nori giữ sợi dây đèn đứt và một bí mật suốt cả năm. Khi hoàng hôn xuống, Nori trút bỏ cả hai, treo dây cờ lên cho mọi người cùng ngắm.",
  "Moonlit feast: one watermelon as big as the moon, a skewer of peaches, and the truth, told kindly.": "Bữa tiệc trăng: một quả dưa hấu to như mặt trăng, một xiên đào và sự thật được nói bằng lòng tử tế.",
  "Under the Old Oak": "Dưới cây sồi già",
  "Hoo! I saw your lanterns from the old oak. Three lights! That hasn’t happened in a year.": "Hú! Từ cây sồi già, ta thấy đèn của các cháu. Ba chiếc! Cả năm rồi mới có lại đấy.",
  "I keep the clearing’s storybook, you know. Every Lantern Night gets a page.": "Ta giữ cuốn truyện của bãi cỏ này. Mỗi Đêm Đèn Lồng đều có một trang riêng.",
  "But first, a riddle supper. Guess my wishes, and I’ll tell you where Hazel really went.": "Nhưng trước hết, hãy dùng bữa cùng câu đố. Đoán đúng món ta muốn, ta sẽ kể Hazel đã đi đâu.",
  "Sunny and sour, shaped like a little boat.": "Vàng như nắng, chua dịu, dáng như chiếc thuyền con.",
  "The colour of the sky just after sunset, with a stone for a heart.": "Mang màu trời vừa tắt nắng, giấu một hạt cứng trong lòng.",
  "Hoo-hoo. A little boat of sunshine… a lemon, dear!": "Hú hú. Chiếc thuyền nhỏ màu nắng… là chanh vàng đó cháu!",
  "Sunset sky, stone heart… a twilight plum, of course.": "Màu trời chạng vạng, hạt cứng trong lòng… là mận hoàng hôn rồi.",
  "Two becoming one. That’s how every good story starts.": "Hai thành một. Truyện hay nào cũng bắt đầu như thế.",
  "Hoo! Clever thing, you guessed it.": "Hú! Giỏi lắm, cháu đoán đúng rồi.",
  "Right again! You read riddles like a book.": "Lại đúng nữa! Cháu giải câu đố như đọc sách ấy.",
  "Pears in a row, like words in a sentence.": "Những quả lê xếp hàng như từng chữ trong câu.",
  "What a plot twist!": "Một bất ngờ thú vị làm sao!",
  "Not in my riddle, but a lovely thought.": "Không phải đáp án, nhưng tấm lòng thật đáng quý.",
  "Now, the story I promised. Hazel is the Lantern Keeper. Not just of this clearing: of every island in the sky.": "Giờ đến câu chuyện ta đã hứa. Hazel là Người Giữ Đèn. Không chỉ ở bãi cỏ này, mà ở mọi hòn đảo trên trời.",
  "Each Lantern Night, the islands light up, so nobody floating out there ever feels alone.": "Mỗi Đêm Đèn Lồng, các hòn đảo cùng thắp sáng, để không ai ngoài kia cảm thấy cô đơn.",
  "Hazel went to wake the far islands. But they only answer a clearing that shines with five.": "Hazel đi đánh thức những hòn đảo xa. Nhưng chúng chỉ hồi đáp khi bãi cỏ sáng đủ năm chiếc đèn.",
  "Then we need one more friend.": "Vậy mình cần thêm một người bạn nữa.",
  "Hoo. I have a feeling they’re closer than you think.": "Hú. Ta có cảm giác người bạn ấy ở gần hơn cháu nghĩ đấy.",
  "A story under the first stars.": "Câu chuyện dưới những vì sao đầu tiên.",
  "Juniper’s storybook has one blank page left. It will be written tonight.": "Cuốn truyện của Juniper còn một trang trắng. Đêm nay, trang ấy sẽ được viết tiếp.",
  "Juniper’s storybook told the truth: Grandma Hazel hadn’t left the clearing behind. She had gone to make sure every island had someone watching for its light.": "Cuốn truyện của Juniper hé lộ sự thật: bà Hazel không bỏ bãi cỏ lại phía sau. Bà đi để mỗi hòn đảo đều có người ngóng ánh đèn của mình.",
  "Storyteller’s supper: two lemons, one twilight plum, and a riddle for dessert.": "Bữa tối người kể chuyện: hai quả chanh vàng, một quả mận hoàng hôn và câu đố làm món tráng miệng.",
  "The Festival of Little Lights": "Lễ hội ánh đèn nhỏ",
  "H-hello. I’m Bramble. I live in the brambles. That’s… that’s why.": "Ch-chào. Mình là Bramble. Mình sống trong bụi mâm xôi. Vì thế… mình mới có tên ấy.",
  "I’ve been watching all evening. Sorry. I’m not very good at coming out.": "Mình đã ngắm mọi người suốt cả buổi. Xin lỗi nhé. Mình không quen bước ra ngoài.",
  "I brought a lantern of my own. It fell into my bush the night the string snapped. I kept it safe.": "Mình mang theo một chiếc đèn. Nó rơi vào bụi cây nhà mình vào đêm dây đứt. Mình đã giữ nó cẩn thận.",
  "…You had it all this time?": "…Bạn giữ nó suốt từ đó sao?",
  "I was too shy to give it back. Could we… light it together?": "Mình ngại quá nên chưa dám trả. Chúng mình… cùng thắp nó nhé?",
  "And… a dragon fruit? It’s the colour of Hazel’s lantern.": "Và… cho mình một quả thanh long nhé? Nó có màu giống chiếc đèn của bà Hazel.",
  "Oh! You knew! Nobody ever guesses what I want.": "Ồ! Bạn biết à! Chưa ai đoán được mình muốn gì cả.",
  "Oh! That was nice.": "Ồ! Hay quá.",
  "Th-thank you.": "C-cảm ơn bạn.",
  "Plums! My favourite. How did you…?": "Mận! Món mình thích nhất. Sao bạn lại…?",
  "Wow…": "Ồ…",
  "That’s okay. Sharing is nice.": "Không sao đâu. Chia sẻ thật vui mà.",
  "It’s… it’s so bright.": "Nó… sáng quá.",
  "Five lanterns, Grandma. Just like you said.": "Năm chiếc đèn rồi, bà ơi. Đúng như bà dặn.",
  "Then let’s give the sky something to answer. Everyone, lanterns up!": "Vậy hãy gửi lời chào lên trời nào. Mọi người ơi, thả đèn lên!",
  "A clearing full of friends.": "Bãi cỏ đầy bạn bè.",
  "Five lanterns. Five little picnics. Now the whole sky can see.": "Năm chiếc đèn. Năm buổi dã ngoại nhỏ. Giờ cả bầu trời đều nhìn thấy.",
  "Bramble finally stepped out of the brambles, carrying the lantern that started it all. Five lights became a hundred, and far across the sky, someone wrote back.": "Bramble cuối cùng cũng bước ra khỏi bụi cây, mang chiếc đèn khởi đầu mọi chuyện. Năm ánh đèn hóa thành hàng trăm, và từ nơi xa trên trời, có người gửi thư về.",
  "Festival feast: a dragon fruit, a pineapple, a skewer of plums, and the courage to say hello.": "Bữa tiệc lễ hội: một quả thanh long, một quả dứa, một xiên mận và lòng can đảm để nói lời chào.",
  "Look! Out past the clouds!": "Nhìn kìa! Phía bên kia những đám mây!",
  "Lights… one after another…": "Ánh đèn… chiếc này nối tiếp chiếc kia…",
  "The far islands. They’re answering.": "Những hòn đảo xa. Họ đang hồi đáp.",
  "One of them is coming this way!": "Có một chiếc đang bay về phía chúng ta!",
  "There’s a letter tied to it.": "Có một lá thư buộc trên đó.",
  "The lanterns of the clearing are lit again, and every island in the sky knows it.": "Đèn lồng ở bãi cỏ lại sáng lên, và mọi hòn đảo trên trời đều biết điều đó.",
  "The Lantern Picnic · Little Keepsakes": "Dã ngoại đèn lồng · Little Keepsakes",
  "The Lantern Picnic": "Dã ngoại đèn lồng",
  "A tiny floating clearing. Five toy friends. One evening. An original 3D fruit picnic: merge, thread skewers, and light the forest together.": "Một bãi cỏ lơ lửng. Năm người bạn đồ chơi. Một buổi tối. Ghép trái cây, làm xiên quả và cùng thắp sáng khu rừng trong buổi dã ngoại 3D.",
  "A floating forest clearing with a picnic cloth. Drag matching fruit together to merge. Drag requested fruit to the plate; thread three matching fruit onto the skewer. N selects, arrows move, Enter places, T serves, K threads, B adds fruit, U undoes, Escape cancels.": "Bãi cỏ trên không với khăn dã ngoại. Kéo trái cây cùng loại lại để ghép. Kéo món khách muốn vào đĩa; xâu ba quả cùng loại vào xiên. N chọn, phím mũi tên di chuyển, Enter đặt, T phục vụ, K xâu, B thêm quả, U hoàn tác, Escape hủy.",
  "Your picnic invitation": "Lời mời dã ngoại của bạn",
  "Show the invitation story": "Xem câu chuyện trong lời mời",
  "Plate wish": "Món khách muốn trên đĩa",
  "Skewer wish": "Món khách muốn trên xiên",
  "Light this lantern to reveal": "Thắp đèn này để nhận",
  "Open the next invitation": "Mở lời mời tiếp theo",
  "golden joys": "xu vàng",
  "Undo last action": "Hoàn tác lượt vừa rồi",
  "Undo (U)": "Hoàn tác (U)",
  "Turn sound on": "Bật âm thanh",
  "Turn sound off": "Tắt âm thanh",
  "Sound": "Âm thanh",
  "Open menu": "Mở trình đơn",
  "Menu": "Trình đơn",
  "Picnic spots": "Các vị trí dã ngoại",
  "Happy basket": "Giỏ vui vẻ",
  "Basket": "Giỏ quả",
  "tap for fresh fruit": "chạm để lấy trái cây",
  "Fruit skewer": "Xiên trái cây",
  "Skewer": "Xiên quả",
  "thread 3 cherries": "xâu 3 quả anh đào",
  "Pip’s plate": "Đĩa của Pip",
  "drop a little wish here": "thả món khách muốn vào đây",
  "NEXT BASKET": "GIỎ QUẢ TIẾP",
  "Drag two cherries together. A little strawberry will grow.": "Kéo hai quả anh đào lại gần nhau để tạo thành dâu tây.",
  "Fruit merge sequence": "Thứ tự ghép trái cây",
  "LITTLE KEEPSAKES PRESENTS": "LITTLE KEEPSAKES GIỚI THIỆU",
  "Five toy friends. One evening. A floating clearing to fill with light.": "Năm người bạn đồ chơi. Một buổi tối. Cùng thắp sáng bãi cỏ trên mây.",
  "Begin the picnic": "Bắt đầu dã ngoại",
  "The Lantern Trail": "Con Đường Đèn Lồng",
  "New · a little adventure": "Mới · chuyến phiêu lưu nhỏ",
  "Journey": "Hành trình",
  "Settings": "Cài đặt",
  "How to play": "Cách chơi",
  "INVITATION I": "LỜI MỜI I",
  "INVITATION I · PIP": "LỜI MỜI I · PIP",
  "Afternoon · The Firefly Clearing": "Buổi chiều · Bãi cỏ đom đóm",
  "Tap to skip": "Chạm để bỏ qua",
  "Conversation": "Trò chuyện",
  "Skip scene": "Bỏ qua cảnh",
  "Next line": "Câu tiếp theo",
  "Next": "Tiếp",
  "Continue": "Tiếp tục",
  "A LITTLE WISH, GRANTED": "MỘT ĐIỀU ƯỚC NHỎ ĐÃ THÀNH",
  "Stars earned": "Số sao nhận được",
  "Actions": "Lượt",
  "Par": "Mốc 3 sao",
  "Joys": "Xu vàng",
  "Welcome the next friend": "Đón người bạn tiếp theo",
  "Stay a little longer": "Ở lại thêm chút nữa",
  "THE END · FOR NOW": "TẠM KHÉP LẠI",
  "Revisit an invitation": "Chơi lại một lời mời",
  "Made with Blender 4.5 and Three.js. Every model, texture, animation and sound is original.": "Được tạo bằng Blender 4.5 và Three.js. Mô hình, chất liệu, chuyển động và âm thanh đều được sáng tạo riêng.",
  "Close journey": "Đóng hành trình",
  "ONE EVENING IN THE CLEARING": "MỘT BUỔI TỐI Ở BÃI CỎ",
  "Your journey": "Hành trình của bạn",
  "Close settings": "Đóng cài đặt",
  "MAKE IT YOURS": "CHƠI THEO CÁCH CỦA BẠN",
  "✧ Journey & stars": "✧ Hành trình và sao",
  "Graphics": "Đồ họa",
  "Automatic · light on phones, 3D on computers": "Tự động · nhẹ trên điện thoại, 3D trên máy tính",
  "Light · smooth on any device": "Nhẹ · mượt trên mọi thiết bị",
  "3D · low": "3D · thấp",
  "3D · medium": "3D · vừa",
  "3D · high": "3D · cao",
  "3D · ultra": "3D · rất cao",
  "This browser is not saving right now, so the graphics stay as they are.": "Trình duyệt hiện không lưu được, nên đồ họa vẫn giữ nguyên.",
  "3D could not start on this device, so the light stage is open. Settings can switch back to 3D.": "3D không khởi động được trên thiết bị này nên sân khấu nhẹ đã được mở. Bạn có thể chọn lại 3D trong Cài đặt.",
  "Light stage: hand-painted from the 3D clearing, gentle on any device.": "Sân khấu nhẹ: vẽ sẵn từ khu rừng 3D, nhẹ nhàng với mọi thiết bị.",
  "Medium": "Trung bình",
  "High": "Cao",
  "Music": "Nhạc",
  "Effects": "Hiệu ứng",
  "Forest sounds": "Âm thanh khu rừng",
  "Friends’ voices": "Giọng các bạn",
  "Quieter motion (no camera drift, shake or big effects)": "Giảm chuyển động (tắt lướt máy quay, rung và hiệu ứng lớn)",
  "Gentle hints when I pause": "Gợi ý nhẹ nhàng khi tạm dừng",
  "Start the story again": "Bắt đầu lại câu chuyện",
  "Original free play & bubbles": "Chơi tự do và bong bóng (bản cũ, tiếng Anh)",
  "Close help": "Đóng hướng dẫn",
  "WELCOME TO THE CLEARING": "CHÀO MỪNG ĐẾN BÃI CỎ",
  "Make a little room for joy.": "Dành chút chỗ cho niềm vui.",
  "Each friend brings a plate wish and a skewer wish. Grant both to light a lantern and welcome the next friend, a little later in the evening.": "Mỗi người bạn muốn một đĩa trái cây và một xiên quả. Hoàn thành cả hai để thắp một chiếc đèn và đón người bạn tiếp theo khi trời dần tối.",
  "Merge on the cloth.": "Ghép trên khăn.",
  "Drag matching fruit together. Place a third between two, or a fourth inside a triangle. Gold rings show every fruit that will join, and bigger center combos hold a little surprise.": "Kéo các quả cùng loại lại gần nhau. Đặt quả thứ ba giữa hai quả, hoặc quả thứ tư vào giữa tam giác. Vòng vàng đánh dấu các quả sẽ ghép. Ghép nhiều quả ở giữa nhóm sẽ có quà bất ngờ.",
  "Plan a chain.": "Tạo chuỗi ghép.",
  "A new fruit that touches its twin merges again. The preview card shows the final result before you let go.": "Quả vừa tạo chạm vào quả cùng loại sẽ ghép tiếp. Thẻ xem trước cho biết kết quả cuối cùng trước khi bạn thả tay.",
  "Serve and thread.": "Phục vụ và xâu quả.",
  "Drop requested fruit on the plate. Thread three of the pictured fruit onto the wooden skewer. Anything else shared on the plate simply makes room.": "Thả trái cây khách muốn vào đĩa. Xâu ba quả theo hình gợi ý vào que gỗ. Chia sẻ các quả khác vào đĩa chỉ giúp dọn chỗ.",
  "The basket keeps giving.": "Giỏ quả luôn có quà.",
  "Every three merges, servings or threadings, fresh fruit arrives by itself. Tapping the basket brings fruit right away and counts as an action. Rearranging is always free.": "Sau mỗi ba lượt ghép, phục vụ hoặc xâu quả, giỏ tự thêm trái cây. Chạm vào giỏ để lấy ngay sẽ tốn một lượt. Di chuyển để sắp xếp thì luôn miễn phí.",
  "Listen to your guests.": "Lắng nghe các bạn.",
  "Some friends are shy or love a riddle. A wish marked “?” is still a secret: guess it, and they’ll be delighted.": "Có bạn nhút nhát, có bạn thích câu đố. Món có dấu “?” vẫn là bí mật: đoán trúng sẽ khiến khách rất vui.",
  "Stars, if you like.": "Săn sao nếu bạn thích.",
  "Finish at or under par for three stars and find one of Grandma Hazel’s recipe cards. There are no timers and no way to lose.": "Hoàn thành trong hoặc dưới mốc lượt để nhận ba sao và một thẻ công thức của bà Hazel. Không giới hạn thời gian, cũng không có thua cuộc.",
  "Keyboard:": "Bàn phím:",
  "N selects · arrows move · Enter places · T serves · K threads · B basket · U undo · Esc cancels.": "N chọn · mũi tên di chuyển · Enter đặt · T phục vụ · K xâu · B giỏ quả · U hoàn tác · Esc hủy.",
  "Back to the clearing": "Về bãi cỏ",
  "Loading": "Đang tải",
  "Unpacking handmade toys…": "Đang mở hộp đồ chơi thủ công…",
  "Stitching the picnic cloth…": "Đang trải khăn dã ngoại…",
  "Hanging paper lanterns…": "Đang treo đèn lồng giấy…",
  "Waking the fireflies…": "Đang đánh thức đom đóm…",
  "A little light for Pip": "Ánh đèn nhỏ cho Pip",
  "“I kept a place for you. Shall we make something sweet?”": "“Mình đã giữ chỗ cho bạn. Cùng làm món gì ngọt nhé?”",
  "A berry welcome": "Dâu tây đón khách",
  "The first lantern": "Chiếc đèn đầu tiên",
  "A seat for someone new": "Chỗ ngồi cho bạn mới",
  "“I followed the light. Is there room for one more?”": "“Mình theo ánh đèn đến đây. Còn chỗ cho một người nữa không?”",
  "A taste of sunshine": "Hương vị nắng",
  "A pot of moonflower tea": "Ấm trà hoa trăng",
  "The lanterns we share": "Những chiếc đèn chung vui",
  "“The clearing used to be so quiet. Look at it now.”": "“Bãi cỏ trước đây yên tĩnh lắm. Giờ thì nhìn xem.”",
  "A moonlit feast": "Bữa tiệc trăng",
  "Nori’s paper bunting": "Dây cờ giấy của Nori",
  "Stories after sundown": "Chuyện kể sau hoàng hôn",
  "“Hoo! I saw your lanterns from the old oak. Will you stay for a story?”": "“Hú! Từ cây sồi già ta đã thấy đèn của các cháu. Ở lại nghe chuyện nhé?”",
  "A storyteller’s supper": "Bữa tối người kể chuyện",
  "Juniper’s storybook": "Cuốn truyện của Juniper",
  "The festival of little lights": "Lễ hội ánh đèn nhỏ",
  "“I’m a little shy… but I brought a lantern of my own.”": "“Mình hơi nhút nhát… nhưng mình mang theo một chiếc đèn.”",
  "A festival feast": "Bữa tiệc lễ hội",
  "A sky full of lanterns": "Bầu trời đầy đèn lồng",
  "Cherries": "Anh đào",
  "Strawberry": "Dâu tây",
  "Grapes": "Nho",
  "Orange": "Cam",
  "Lemon": "Chanh vàng",
  "Pear": "Lê",
  "Peach": "Đào",
  "Pineapple": "Dứa",
  "Watermelon": "Dưa hấu",
  "Ruby apple": "Táo hồng ngọc",
  "Apple": "Táo",
  "Twilight plum": "Mận hoàng hôn",
  "Plum": "Mận",
  "Dragon fruit": "Thanh long",
  "Afternoon": "Buổi chiều",
  "Golden hour": "Nắng vàng",
  "Sunset": "Hoàng hôn",
  "Dusk": "Chạng vạng",
  "Night": "Đêm",
  "Language": "Ngôn ngữ",
  "A clearing full of friends": "Bãi cỏ đầy bạn bè",
  "A secret wish": "Món ước bí mật",
  "{guest} hasn’t asked yet": "{guest} chưa ngỏ lời",
  "A riddle for {guest}’s plate": "Câu đố cho đĩa của {guest}",
  " · {count} wanted": " · cần {count} quả",
  "for {guest}’s plate": "cho đĩa của {guest}",
  "{fruit} skewer": "Xiên {fruit}",
  "✓ served": "✓ đã phục vụ",
  "{count} star pace": "Tiến độ {count} sao",
  "actions · par": "lượt · mốc",
  "best {stars}": "tốt nhất {stars}",
  "{guest}’s plate": "Đĩa của {guest}",
  "a wish, served": "đã xong món ước",
  "thread 3 {fruit}": "xâu 3 quả {fruit}",
  "Picnic complete": "Đã xong buổi dã ngoại",
  "in {count} action": "sau {count} lượt",
  "in {count} actions": "sau {count} lượt",
  "make a little room": "dọn thêm chút chỗ",
  "Next delivery: {fruit}": "Lần tới: {fruit}",
  " · wished for": " · khách đang muốn",
  "See the festival ✧": "Ngắm lễ hội ✧",
  "Back to the festival": "Về lễ hội",
  "Welcome {guest}": "Chào đón {guest}",
  "everyone": "mọi người",
  "Story complete · {stars} of {total} stars": "Xong câu chuyện · {stars}/{total} sao",
  "Invitation {roman} of {last} · {guest} is waiting": "Lời mời {roman}/{last} · {guest} đang chờ",
  "INVITATION {roman} · {guest}": "LỜI MỜI {roman} · {guest}",
  " · REVISIT": " · CHƠI LẠI",
  "Return to the festival": "Trở về lễ hội",
  "Continue the picnic": "Tiếp tục dã ngoại",
  "Playing without a save in this browser.": "Trình duyệt này không thể lưu tiến độ.",
  "Arrange matching fruit. Thread a skewer. Share a little happiness.": "Xếp quả cùng loại. Làm một xiên quả. Chia sẻ chút niềm vui.",
  "{count}-fruit merge": "Ghép {count} quả",
  "{count}-step chain": "Chuỗi {count} bước",
  "{merge}{chain} {outputs} · +{reward} joys.": "{merge}{chain} {outputs} · +{reward} xu.",
  "Three little fruits, one lovely skewer. Served with love.": "Ba quả nhỏ, một xiên xinh. Gửi trọn yêu thương.",
  "{count} of 3 on the skewer. Keep threading the same fruit.": "Đã xâu {count}/3 quả. Tiếp tục xâu quả cùng loại nhé.",
  "{guest} gasps. You guessed a secret wish!": "{guest} ngạc nhiên. Bạn đoán trúng món bí mật rồi!",
  "{guest} loved that. One wish closer to a lantern.": "{guest} thích lắm. Thêm một món nữa là gần tới ánh đèn.",
  "A little extra for the table. You made room for something new.": "Thêm chút quà cho cả bàn. Bạn đã dọn chỗ cho món mới.",
  "No room for the new fruit there. Make a little space first.": "Chưa đủ chỗ cho quả mới ở đó. Dọn chút chỗ trước nhé.",
  "No room for the merged fruit there. Clear a little space first.": "Không đủ chỗ cho quả sau khi ghép. Dọn chút chỗ trước nhé.",
  "A lovely spot. Rearranging never uses an action.": "Chỗ đẹp đấy. Sắp xếp không tốn lượt.",
  "Fresh fruit! Asking the basket uses an action; it also refills by itself every three.": "Trái cây mới đây! Lấy từ giỏ tốn một lượt; giỏ cũng tự thêm quả sau mỗi ba lượt.",
  "One little step back. The whole action is restored.": "Lùi lại một bước. Đã hoàn tác trọn vẹn lượt vừa rồi.",
  "✧ Bloom combo! {fruit} ×{count} became {outputs} · +{reward} joys.": "✧ Ghép nở hoa! {fruit} ×{count} thành {outputs} · +{reward} xu.",
  "✧ You found a secret: fruit merged in the middle of a group bloom into bonus fruit!": "✧ Bạn tìm ra bí mật rồi: ghép vào giữa nhóm sẽ nở thêm quả thưởng!",
  "Oh! It bloomed into more than we started with!": "Ồ! Nở ra nhiều quả hơn ban đầu luôn!",
  "Offer it to {guest}?": "Mời {guest} món này nhé?",
  "Maybe it’s the wish…": "Biết đâu đúng món khách muốn…",
  "✧ Bloom combo": "✧ Ghép nở hoa",
  "A wish, fulfilled": "Đã xong món khách muốn",
  "Serve to {guest} · +60 joys": "Mời {guest} · +60 xu",
  "Share to make room": "Chia sẻ để dọn chỗ",
  "Not on today’s wish": "Không phải món khách đang muốn",
  "Thread fruit {count} of 3": "Xâu quả thứ {count}/3",
  "Complete the skewer · +120 joys": "Hoàn thành xiên · +120 xu",
  "Save it for the skewer": "Để dành cho xiên quả",
  "Skewer already served": "Xiên đã được phục vụ",
  "This stick wants {fruit}": "Xiên này cần {fruit}",
  "Finish the plate wish.": "Hoàn thành món trên đĩa nhé.",
  "Drop here to keep your fruit where it was.": "Thả ở đây để giữ quả tại chỗ cũ.",
  "{fruit}! That’s the answer to {guest}’s riddle.": "{fruit}! Đó là đáp án câu đố của {guest}.",
  "Drag two {fruit} together. Two little things make one bigger thing.": "Kéo hai quả {fruit} lại với nhau. Hai thứ nhỏ thành một thứ lớn hơn.",
  "{fruit} is on {guest}’s wish. Drag it to the plate.": "{guest} đang muốn {fruit}. Kéo quả vào đĩa nhé.",
  "{fruit} would look lovely on the skewer.": "Quả {fruit} sẽ rất đẹp trên xiên đấy.",
  "Two {fruit} would make {next}.": "Hai quả {fruit} sẽ thành {next}.",
  "Tap the basket for fresh fruit. It uses an action, so merge first if you can.": "Chạm giỏ để lấy thêm trái cây. Sẽ tốn một lượt, nên hãy ghép trước nếu được nhé.",
  "A PICNIC, REVISITED": "MỘT BUỔI DÃ NGOẠI CHƠI LẠI",
  "INVITATION {roman} · COMPLETE": "LỜI MỜI {roman} · HOÀN THÀNH",
  " · Hazel’s recipe card found": " · Đã tìm thấy thẻ công thức của bà Hazel",
  "✧ Keepsake:": "✧ Kỷ vật:",
  "new best": "kỷ lục mới",
  "Light the festival": "Thắp sáng lễ hội",
  "{count} of 3 stars": "{count}/3 sao",
  "The festival glows on. Revisit any invitation from the Journey.": "Lễ hội vẫn sáng rực. Chơi lại lời mời bất kỳ trong Hành trình nhé.",
  "INVITATION {roman} OF {last}": "LỜI MỜI {roman}/{last}",
  "You gathered {score} golden joys and {stars} of {total} stars.": "Bạn đã nhận {score} xu vàng và {stars}/{total} sao.",
  "Lit": "Đã thắp sáng",
  "Every lantern is lit. {stars} of {total} stars · {recipes} of {chapters} of Hazel’s recipe cards. Revisit any picnic to beat your best.": "Tất cả đèn đã sáng. {stars}/{total} sao · {recipes}/{chapters} thẻ công thức của bà Hazel. Chơi lại để lập kỷ lục mới nhé.",
  "Light all five lanterns to finish the story. Three stars on an invitation finds one of Grandma Hazel’s recipe cards.": "Thắp cả năm chiếc đèn để hoàn thành câu chuyện. Nhận ba sao ở mỗi lời mời để tìm thẻ công thức của bà Hazel.",
  "Leave this revisit": "Rời màn chơi lại",
  "{stars} · best {actions} actions · par {par}": "{stars} · tốt nhất {actions} lượt · mốc {par}",
  "In progress": "Đang chơi",
  "Not yet lit": "Chưa thắp sáng",
  "Three stars here finds one of Hazel’s recipe cards.": "Nhận ba sao ở đây để tìm thẻ công thức của bà Hazel.",
  "A friend yet to arrive": "Một người bạn chưa đến",
  "Revisit": "Chơi lại",
  "Back at the festival. The lanterns glow on.": "Trở lại lễ hội. Đèn lồng vẫn tỏa sáng.",
  "Rendering at {quality} quality{resolution}.": "Chất lượng hình ảnh: {quality}{resolution}.",
  " · resolution {percent}% to keep things smooth": " · độ phân giải {percent}% để chơi mượt hơn",
  "Low": "Thấp",
  "Ultra": "Rất cao",
  "Replace this story and all stars? Tap again.": "Xóa câu chuyện và mọi sao đã nhận? Chạm lần nữa.",
  "Sound is unavailable in this browser.": "Trình duyệt này không hỗ trợ âm thanh.",
  "Drag three {fruit} onto the bamboo skewer.": "Kéo ba quả {fruit} vào xiên tre.",
  "Drop the pictured wishes onto {guest}’s plate. Other fruit makes room.": "Thả món trong hình vào đĩa của {guest}. Quả khác sẽ giúp dọn chỗ.",
  "A well-earned rest. Continue from the invitation whenever you like.": "Nghỉ ngơi chút nhé. Bấm lời mời để tiếp tục khi bạn muốn.",
  "The clearing needs a little help.": "Bãi cỏ đang cần chút trợ giúp.",
  "Try again": "Thử lại",
  "Open the original picnic": "Mở bản dã ngoại cũ (tiếng Anh)",
  "{score} little joys earned": "Đã nhận {score} xu vàng",
  "Make a little room by merging or serving fruit.": "Ghép hoặc phục vụ trái cây để dọn thêm chỗ nhé.",
  "Your skewer is already served. Follow the plate wish.": "Xiên đã được phục vụ. Hãy làm món khách muốn trên đĩa.",
  "This skewer needs three {fruit}.": "Xiên này cần ba quả {fruit}.",
  "Your lantern is lit. Open the next invitation.": "Đèn của bạn đã sáng. Mở lời mời tiếp theo nhé.",
  "Drag the requested fruit to this plate. Other fruit can be shared to make room.": "Kéo quả khách muốn vào đĩa này. Chia sẻ các quả khác để dọn chỗ.",
  "{fruit} picked up. Tap a matching fruit, the plate, the skewer or a new spot.": "Đã nhấc {fruit}. Chạm quả cùng loại, đĩa, xiên hoặc vị trí mới.",
  "{fruit} picked up. Arrow keys move; Enter places; T serves; K threads.": "Đã nhấc {fruit}. Mũi tên di chuyển; Enter đặt; T phục vụ; K xâu.",
  // Hazel's Trunk and the 1.2 settings layout
  "Open Hazel’s Trunk": "Mở rương của bà Hazel",
  "Hazel’s Trunk": "Rương của bà Hazel",
  "Visit Hazel’s Trunk": "Ghé rương của bà Hazel",
  "Close Hazel’s Trunk": "Đóng rương của bà Hazel",
  "KEEPSAKES FOR THE CLEARING": "KỶ VẬT CHO BÃI CỎ",
  "Spend golden joys on keepsakes for the picnic. The trunk keeps everything, even if you start the story again.": "Dùng xu vàng đổi lấy kỷ vật cho buổi dã ngoại. Rương giữ lại mọi thứ, kể cả khi bạn bắt đầu lại câu chuyện.",
  "golden joys to spend": "xu vàng có thể tiêu",
  "Keepsakes": "Kỷ vật",
  "Blankets": "Khăn trải",
  "Lanterns": "Đèn lồng",
  "More": "Thêm",
  "Display": "Hiển thị",
  "Play": "Lối chơi",
  "Quieter motion": "Giảm chuyển động",
  "No camera drift, shake or big effects": "Tắt lướt máy quay, rung và hiệu ứng lớn",
  "Gentle hints": "Gợi ý nhẹ nhàng",
  "A nudge when you pause": "Nhắc khẽ khi bạn tạm dừng",
  "✓ On the picnic": "✓ Đang dùng",
  "Use it": "Dùng",
  "Buy {item} for {price} golden joys": "Mua {item} với {price} xu vàng",
  "In use": "Đang dùng",
  "{count} more golden joys needed.": "Cần thêm {count} xu vàng.",
  "{item} is on the picnic now.": "{item} đã được bày ra buổi dã ngoại.",
  "Cornflower gingham": "Khăn caro xanh thanh cúc",
  "Grandma Hazel’s own picnic blanket.": "Chiếc khăn dã ngoại của chính bà Hazel.",
  "Strawberry check": "Khăn caro dâu tây",
  "Red and cream, like every picnic in every storybook.": "Đỏ và kem, như mọi buổi dã ngoại trong truyện cổ tích.",
  "Meadow plaid": "Khăn kẻ đồng cỏ",
  "Sage and butter yellow, woven for long summer afternoons.": "Xanh lá xô thơm và vàng bơ, dệt cho những buổi chiều hè dài.",
  "Honeycomb quilt": "Chăn ghép tổ ong",
  "Patchwork in warm honey and marigold.": "Những mảnh ghép màu mật ong và cúc vạn thọ ấm áp.",
  "Cream paper": "Giấy màu kem",
  "The clearing’s classic glow.": "Ánh sáng quen thuộc của bãi cỏ.",
  "Peach blossom": "Hoa đào",
  "A rosy glow for warm evenings.": "Ánh hồng cho những buổi tối ấm áp.",
  "Mint leaf": "Lá bạc hà",
  "Cool green light, fresh as the pond.": "Ánh xanh mát, trong lành như mặt hồ.",
  "Starlight blue": "Xanh ánh sao",
  "The colour of the far islands answering.": "Màu của những hòn đảo xa đáp lời.",
  "Revisit {title}": "Chơi lại {title}",
};
