import { Room } from './scene.js';
import { Soundscape } from './audio.js';
import { SAVE_KEY,TREASURES,RESTORATIONS,DECORATIONS,LEVELS,newGame,loadGame,levelFor,collect,restore,buyDecoration,claimBonus } from './game.js';
import { icon } from './icons.js';

const $=id=>document.getElementById(id);
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));
let storageAvailable=true,raw=null;
try{raw=localStorage.getItem(SAVE_KEY);}catch{storageAvailable=false;}
const state=loadGame(raw);
if(!raw)state.reducedMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const sound=new Soundscape();let room,selected=null,toastTimer,speechTimer,moved=false,modalOrigin=null;
const modal=$('modal');
function save(){try{localStorage.setItem(SAVE_KEY,JSON.stringify(state));storageAvailable=true;}catch{storageAvailable=false;}$('save-status').innerHTML=`<span class="small-dot"></span> ${storageAvailable?'Saved on this device':'Playing without a save'}`;}
function toast(message){$('toast').textContent=message;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3400);$('announcer').textContent=message;}
function speak(message,ms=5600){$('speech').textContent=message;$('speech').classList.remove('hidden');clearTimeout(speechTimer);speechTimer=setTimeout(()=>$('speech').classList.add('hidden'),ms);}
function announceMove(){if(!moved){moved=true;$('movement-hint').style.opacity='.35';$('speech').classList.add('hidden');}if(!$('interaction').hidden){$('interaction').hidden=true;selected=null;}}
function onCollect(id){const previous=levelFor(state.xp);const result=collect(state,id);if(!result.ok)return;const treasure=TREASURES.find(t=>t.id===id);sound.discover();room.sync();updateUI();save();speak(treasure.thought);floatingReward(treasure,'+1 thread  ·  +5 buttons');if(levelFor(state.xp).index>previous.index)setTimeout(()=>toast(`Pip is growing: ${levelFor(state.xp).name} · Level ${levelFor(state.xp).index+1}`),900);else if(state.thread===3)toast('Enough thread for a little kindness. Follow the leaf on your purpose card.');}
function floatingReward(item,text){const el=document.createElement('div');el.className='floating-reward';el.textContent=text;const p=room.project({x:item.x,y:.65,z:item.z});el.style.left=`${p.x}px`;el.style.top=`${p.y}px`;$('markers').append(el);setTimeout(()=>el.remove(),1900);}
function updateUI(){
  $('coins').textContent=state.coins;$('pocket-count').textContent=state.thread;
  const level=levelFor(state.xp);$('level-number').textContent=`LV. ${level.index+1}`;$('level-name').textContent=level.name;
  $('xp-fill').style.width=`${level.next?Math.min(100,(state.xp-level.min)/(level.next-level.min)*100):100}%`;$('xp-label').textContent=`${state.xp} wonder. ${level.next?`${level.next-state.xp} until next level.`:'Fully grown for this chapter.'}`;
  $('restored-count').textContent=`${state.restored.length} of 3 memories found`;
  const current=RESTORATIONS.find(t=>!state.restored.includes(t.id));
  if(current){$('quest-title').textContent=current.title;$('quest-count').textContent=`0${state.restored.length+1} / 03`;$('quest-description').textContent=["A sleepy lamp. A few loose threads. Perhaps we can make it glow again.","There is a song hiding in that little box. Let’s help it find its way out.","An old friend is missing a stitch. Some things are too loved to leave behind."][state.restored.length];$('thread-count').textContent=`${state.thread} / ${current.cost} pieces of thread`;$('quest-checks').textContent=Array.from({length:3},(_,i)=>i<Math.min(3,state.thread)?'●':'○').join(' ');$('guide-button').innerHTML=`${state.thread>=current.cost?current.short:'Find a treasure'} ${icon('arrow')}`;
  }else{$('quest-title').textContent='Some love travels with you.';$('quest-count').textContent='03 / 03';$('quest-description').textContent='Every keepsake has found its story. Now make this little corner feel like home.';$('thread-count').textContent='A room full of memories';$('quest-checks').textContent='● ● ●';$('guide-button').innerHTML=`${state.bonusClaimed?'Make yourself at home':'A gift for your kindness'} ${icon(state.bonusClaimed?'flower':'gift')}`;}
  for(const item of RESTORATIONS){const button=$(`marker-${item.id}`);if(!button)continue;const done=state.restored.includes(item.id);button.classList.toggle('restored',done);button.classList.toggle('locked',!!item.requires&&!state.restored.includes(item.requires));button.innerHTML=icon(done?'check':item.id==='lamp'?'sun':item.id==='music'?'spark':'heart');button.setAttribute('aria-label',`${done?'Remember':'Visit'} ${item.name}`);}
  $('sound-button').innerHTML=icon(state.sound?'sound':'mute');$('sound-button').setAttribute('aria-label',state.sound?'Turn sound off':'Turn sound on');$('sound-button').setAttribute('aria-pressed',String(state.sound));
  if(selected)showInteraction(selected);sound.music=state.restored.includes('music');
}
function showInteraction(id){
  const item=RESTORATIONS.find(t=>t.id===id);if(!item)return;
  if(state.restored.includes(id)){showMemory(id,false);return;}
  selected=id;$('interaction').hidden=false;$('interaction-title').textContent=item.name;
  const locked=item.requires&&!state.restored.includes(item.requires);const can=state.thread>=item.cost&&!locked;
  $('interaction-description').textContent=locked?`A little patience. First, ${RESTORATIONS.find(t=>t.id===item.requires).short.toLowerCase()}.`:can?'A few careful stitches. A little of your heart.':`This needs ${item.cost} pieces of thread. Pip has ${state.thread}. Explore the room to find more.`;
  $('restore-button').disabled=!can;$('restore-button').innerHTML=`${icon('thread')} Restore with ${item.cost} thread`;
}
function closeInteraction(){$('interaction').hidden=true;selected=null;}
function showModal(html){closeInteraction();modalOrigin=document.activeElement;$('modal-content').innerHTML=html;if(!modal.open)modal.showModal();room?.setPaused(true);document.querySelectorAll('.nav-button').forEach(b=>b.classList.remove('active'));}
function closeModal(){modal.close();}
modal.addEventListener('close',()=>{room?.setPaused(document.hidden);document.querySelectorAll('.nav-button').forEach(b=>b.classList.remove('active'));$('explore-button').classList.add('active');modalOrigin?.focus?.({preventScroll:true});});
modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeModal();}});
$('close-modal').addEventListener('click',closeModal);
function showMemory(id,isNew){const item=RESTORATIONS.find(t=>t.id===id);showModal(`<article class="memory"><div class="modal-emblem">${icon(id==='lamp'?'sun':id==='music'?'spark':'heart')}</div><span class="eyebrow">${item.subtitle}</span><h2 id="modal-title">${item.title}</h2><blockquote>${item.quote}</blockquote><div class="memory-divider">· ✧ ·</div><p>${item.text}</p>${isNew?`<div class="reward-line">${icon('coin')} +20 buttons ${icon('spark')} +20 wonder</div>`:''}<button id="memory-continue" class="primary-button">${isNew&&id==='bear'?'See what comes next':'Keep this close'} ${icon('arrow')}</button></article>`);$('memory-continue').addEventListener('click',()=>{if(isNew&&id==='bear')showEnding();else{closeModal();speak(item.after,7500);}});}
function showEnding(){showModal(`<article class="memory"><div class="modal-emblem">${icon('home')}</div><span class="eyebrow">CHAPTER ONE · A NEW LITTLE BEGINNING</span><h2 id="modal-title">Some love<br>travels with you.</h2><p>The lamp is glowing. The old song is playing.<br>And on a box by the door, Ada has written:<br><em>“The things we keep.”</em></p><blockquote>Growing up does not mean<br>leaving every good thing behind.</blockquote><p>You helped Pip remember where they belong.<br>This first little chapter is complete.</p><div class="ending-options">${!state.bonusClaimed?`<button class="primary-button" id="claim-gift">${icon('gift')} Open a thank-you gift · 40 buttons</button>`:`<button class="primary-button" id="ending-decorate">${icon('flower')} Make this room yours</button>`}<button class="secondary-button" id="ending-stay">Stay a little longer</button></div><div class="modal-footnote">There is no hurry here.</div></article>`);$('ending-stay').onclick=closeModal;if($('claim-gift'))$('claim-gift').onclick=()=>{const result=claimBonus(state);if(result.ok){sound.restore();save();updateUI();toast('A thank-you from Pip · 40 buttons for your little home');showEnding();}};if($('ending-decorate'))$('ending-decorate').onclick=showShop;}
function showPocket(){showModal(`<span class="eyebrow">SMALL THINGS, BIG POSSIBILITIES</span><h2 id="modal-title">Pip’s little pocket</h2><p>Every discovery leaves a little thread of wonder. Use the thread to mend keepsakes; the memories stay with you.</p><div class="collection-grid">${TREASURES.map(t=>{const found=state.collected.includes(t.id);return `<div class="pocket-item ${found?'':'unknown'}" style="--item-color:${t.color}">${icon(found?(t.kind==='spool'?'thread':t.kind==='button'?'coin':'spark'):'help')}<span>${found?t.name:'Yet to be found'}</span></div>`;}).join('')}</div><div class="inventory-stats"><span>${icon('thread')} ${state.thread} thread left</span><span>${icon('spark')} ${state.collected.length} / 9 discoveries</span></div>`);$('pocket-button').classList.add('active');}
function showMemories(){showModal(`<span class="eyebrow">THE THINGS THAT STAY WITH US</span><h2 id="modal-title">A book of small memories</h2><p>Three quiet stories, tucked away in an ordinary room. Restore a keepsake to hear what it remembers.</p>${RESTORATIONS.map((t,i)=>{const found=state.restored.includes(t.id);return `<button class="memory-entry" ${found?'':'disabled'} data-memory="${t.id}"><span class="entry-number">0${i+1}</span><span><h3>${found?t.title:'A memory waiting'}</h3><small>${found?t.subtitle.split(' · ')[1]:t.short}</small></span>${icon(found?'arrow':'book')}</button>`;}).join('')}<div class="modal-footnote">${state.restored.length} of 3 memories safely kept.</div>`);document.querySelectorAll('[data-memory]').forEach(b=>b.onclick=()=>showMemory(b.dataset.memory,false));$('memories-button').classList.add('active');}
function showShop(){showModal(`<span class="eyebrow">A CORNER OF THE WORLD, ALL YOURS</span><h2 id="modal-title">Make yourself at home.</h2><p>Trade the buttons you have earned for little touches of warmth. Every choice appears in your room.</p><div class="reward-line">${icon('coin')} ${state.coins} buttons in your pocket</div>${DECORATIONS.map(t=>{const owned=state.decorations.includes(t.id);return `<div class="shop-item"><div class="shop-art">${icon(t.icon)}</div><div><h3>${t.name}</h3><p>${t.description}</p></div><button class="primary-button" data-buy="${t.id}" ${owned||state.coins<t.cost?'disabled':''}>${icon(owned?'check':'coin')} ${owned?'At home':t.cost}</button></div>`;}).join('')}<div class="modal-footnote">Earned by exploring. Given with kindness.</div>`);document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>{if(buyDecoration(state,b.dataset.buy).ok){room.sync();save();updateUI();sound.discover();toast(`${DECORATIONS.find(t=>t.id===b.dataset.buy).name} is now in your room.`);showShop();}});$('decorate-button').classList.add('active');}
function showHelp(){showModal(`<span class="eyebrow">NO HURRY. NO WRONG TURNS.</span><h2 id="modal-title">A little guide to wonder.</h2><ul class="help-list"><li>${icon('compass')}<span><strong>Wander with Pip</strong>Tap or click the floor to walk. Pip picks up little treasures nearby. On a keyboard, use arrow keys or WASD.</span></li><li>${icon('thread')}<span><strong>Turn finding into kindness</strong>Each treasure gives 1 thread, 5 buttons, and 8 wonder. Visit a keepsake marker and use 3 thread to repair it. Press E to approach a nearby keepsake.</span></li><li>${icon('book')}<span><strong>Let the room tell its story</strong>Restore the lamp, the music box, then the bear. Each reveals a memory, warms the room, and gives Pip confidence.</span></li><li>${icon('flower')}<span><strong>Make a little home</strong>Spend earned buttons on decorations. Your progress saves in this browser. You can leave and return whenever you like.</span></li></ul><label class="settings-line"><input type="checkbox" id="motion-setting" ${state.reducedMotion?'checked':''}> Quiet motion · reduce decorative animation</label><button id="help-done" class="primary-button">Let’s wander ${icon('arrow')}</button><button id="reset-game" class="subtle-button">Start this chapter again</button>`);$('help-done').onclick=closeModal;$('motion-setting').onchange=e=>{state.reducedMotion=e.target.checked;document.body.classList.toggle('quiet-motion',state.reducedMotion);room.sync();save();};$('reset-game').onclick=showReset;}
function showReset(){showModal(`<span class="eyebrow">A FRESH LITTLE BEGINNING</span><h2 id="modal-title">Begin again?</h2><p>This clears your discoveries, memories, buttons, and decorations from this browser. Pip’s first afternoon will begin again.</p><div class="ending-options"><button class="primary-button" id="keep-progress">Keep my little world</button><button class="secondary-button" id="confirm-reset">Yes, start this chapter again</button></div>`);$('keep-progress').onclick=closeModal;$('confirm-reset').onclick=()=>{try{localStorage.removeItem(SAVE_KEY);}catch{}Object.assign(state,newGame());save();location.reload();};}
$('guide-button').onclick=()=>{closeInteraction();const next=RESTORATIONS.find(t=>!state.restored.includes(t.id));if(!next){state.bonusClaimed?showShop():showEnding();return;}if(state.thread>=next.cost){room.goToKeepsake(next.id);return;}const available=TREASURES.filter(t=>!state.collected.includes(t.id)).sort((a,b)=>room.distanceTo(a)-room.distanceTo(b));if(available.length){room.goTo(available[0].x,available[0].z);toast(`Pip is curious about ${available[0].name.toLowerCase()}.`);}};
$('restore-button').onclick=()=>{if(!selected)return;const id=selected;const result=restore(state,id);if(!result.ok){toast(result.reason);return;}room.sync();save();selected=null;updateUI();sound.restore();closeInteraction();const item=RESTORATIONS.find(t=>t.id===id);room.burst(item.x,item.z);showMemory(id,true);};
$('close-interaction').onclick=closeInteraction;
$('explore-button').onclick=()=>{if(modal.open)closeModal();closeInteraction();$('scene').focus({preventScroll:true});};
$('pocket-button').onclick=showPocket;$('memories-button').onclick=showMemories;$('decorate-button').onclick=showShop;$('help-button').onclick=showHelp;
$('sound-button').onclick=()=>{state.sound=!state.sound;try{sound.setEnabled(state.sound);}catch{state.sound=false;toast('Audio is unavailable in this browser. You can still enjoy the room.');}updateUI();save();};
$('zoom-in').onclick=()=>room.setZoom(.1);$('zoom-out').onclick=()=>room.setZoom(-.1);
$('photo-button').onclick=()=>{const a=document.createElement('a');a.href=room.photo();a.download='little-keepsakes-my-attic.png';a.click();toast('A little moment, saved as a photo.');};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.open)closeInteraction();if(e.key==='?'&&!modal.open)showHelp();});
document.addEventListener('visibilitychange',()=>{save();room?.setPaused(document.hidden||modal.open);});window.addEventListener('pagehide',save);setInterval(save,4000);
function createMarkers(){for(const item of RESTORATIONS){const b=document.createElement('button');b.id=`marker-${item.id}`;b.className='world-marker';b.title=item.name;b.onclick=()=>{if(!modal.open)room.goToKeepsake(item.id);};$('markers').append(b);}}
function placeMarkers(){for(const item of RESTORATIONS){const p=room.project({x:item.id==='lamp'?-3.45:item.id==='music'?2.65:-.25,y:item.id==='lamp'?2.55:item.id==='music'?1.55:1.9,z:item.id==='lamp'?-2.25:item.id==='music'?-.95:-2.86});const button=$(`marker-${item.id}`);button.style.left=`${p.x}px`;button.style.top=`${p.y}px`;}const p=room.project({x:room.position.x,y:1.3,z:room.position.z});const width=room.canvas.clientWidth;const bubbleWidth=$('speech').offsetWidth;$('speech').style.left=`${Math.max(8,Math.min(width-bubbleWidth-8,p.x+15))}px`;$('speech').style.top=`${Math.max(0,p.y-60)}px`;}
try {
  room=new Room($('scene'),state,{onCollect,onInteract:showInteraction,onMove:announceMove,onReady:()=>{requestAnimationFrame(()=>$('loading').classList.add('loaded'));}});
  createMarkers();room.onFrame=placeMarkers;updateUI();save();
  document.body.classList.toggle('quiet-motion',state.reducedMotion);
  if(raw)speak(state.restored.length===3?'Welcome back. It feels like home in here.':'You came back. I kept our little world safe.',6500);else speechTimer=setTimeout(()=>$('speech').classList.add('hidden'),10000);
  if(state.sound)document.addEventListener('pointerdown',()=>sound.setEnabled(true),{once:true});
  // Read-only diagnostics for local development and accessibility QA.
  if(new URLSearchParams(location.search).has('debug'))window.__keepsakes={getState:()=>structuredClone(state),project:(p)=>room.project(p),getPosition:()=>({x:room.position.x,z:room.position.z}),getRenderStats:()=>({...room.renderer.info.render}),isWalkable:(x,z)=>room.isWalkable(x,z),pathTo:(x,z)=>room.pathTo(x,z).map(p=>({x:p.x,z:p.z}))};
}catch(error){console.error(error);$('loading').innerHTML=`<div class="fatal-error"><span class="loading-star">✧</span><h2>This little world needs WebGL.</h2><p>Try a recent browser with hardware acceleration enabled, then come back to meet Pip.</p><button class="primary-button" id="retry">Try again</button></div>`;$('retry').onclick=()=>location.reload();for(const id of ['guide-button','zoom-in','zoom-out','photo-button'])$(id).disabled=true;}
