import {PicnicScene} from './picnic-scene.js';
import {Soundscape} from './audio.js';
import {icon} from './icons.js';
import {fruitIcon} from './fruit-icons.js';
import {picnicIcon,itemIcon} from './picnic-wishes-icons.js';
import {coinIcon,PicnicCoins} from './picnic-coins.js';
import {PICNIC_SAVE_KEY,FRUITS,FRUIT_ORDER,PICNIC_ITEMS,PLATE,BASKET,BUBBLE_JAR,GIFTS,allItems,itemInfo,family,catalogue,introduceBubbles,newPicnic,loadPicnic,dropFruit,addFruit,addBubble,movePip} from './picnic-game.js';
import {CHALLENGE_SAVE_KEY,newChallenge,loadChallenge,dropChallenge,upcomingFruit,GOAL,DROP_EVERY} from './picnic-challenge.js';
const $=id=>document.getElementById(id);
document.querySelectorAll('[data-icon]').forEach(e=>e.innerHTML=icon(e.dataset.icon));$('brand-fruit').innerHTML=fruitIcon(0);$('loading-fruit').innerHTML=fruitIcon(1,66);
const challenge=new URLSearchParams(location.search).get('mode')!=='free',saveKey=challenge?CHALLENGE_SAVE_KEY:PICNIC_SAVE_KEY;
let raw=null;try{raw=localStorage.getItem(saveKey);}catch{}
const state=challenge?loadChallenge(raw):loadPicnic(raw);if(!raw)state.reducedMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
const sound=new Soundscape();sound.music=true;const history=[];let scene,toastTimer,noteTimer,discoveryTimer,preview=null,activeFamily=challenge?'fruit':'picnic';const dialog=$('help-dialog');
$('score-coin').innerHTML=coinIcon(34);
const coins=new PicnicCoins({layer:$('coin-flights'),score:$('score'),counter:document.querySelector('.joy-counter'),total:()=>state.score,quiet:()=>state.reducedMotion,origin:point=>{const p=scene.project(point,.85),rect=scene.canvas.getBoundingClientRect();return{x:rect.x+p.x,y:rect.y+p.y};},onCollect:()=>sound.tone(1318.51,0,.13,.018)});
const hintDefault=challenge?'Drop on a match, or follow the glow between matching fruit.': 'Match two toys, or place one between others for a combo.';
function save(){try{localStorage.setItem(saveKey,JSON.stringify(state));$('save-status').textContent=challenge?'Your challenge is saved':'Your picnic is saved';}catch{$('save-status').textContent='Playing without a save';}}
function toast(text){$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3200);$('announcer').textContent=text;}
function hint(text=hintDefault){$('gesture-hint').innerHTML=`<span class="gesture-dot"></span><span></span>`;$('gesture-hint').lastElementChild.textContent=text;}
function speak(text,ms=5000){$('pip-note').textContent=text;$('pip-note').classList.remove('hidden');clearTimeout(noteTimer);noteTimer=setTimeout(()=>$('pip-note').classList.add('hidden'),ms);}
function renderFamily(){
 const list=catalogue(activeFamily),order=activeFamily==='fruit'?FRUIT_ORDER:list.map((_,i)=>i),known=activeFamily==='picnic'?state.picnicDiscovered:state.discovered;
 const footer=document.querySelector('.fruit-family');footer.dataset.family=activeFamily;
 document.querySelector('.family-eyebrow').textContent=activeFamily==='picnic'?'BUBBLE WISHES':'THE FRUIT FAMILY';
 $('discovery-count').textContent=`${known.length} of ${list.length} discovered`;
 const strip=$('evolution'),scroll=strip.scrollLeft;strip.dataset.family=activeFamily;strip.tabIndex=0;
 strip.setAttribute('aria-label',activeFamily==='picnic'?'Bubble and picnic treasure growth sequence':'Fruit combination sequence. Scroll to explore all twelve fruit.');
 strip.innerHTML=order.map((level,i)=>{
  const f=list[level],next=order[i+1],title=next!==undefined?`Match ${f.name.toLowerCase()} to make ${list[next].name.toLowerCase()}. Larger groups earn more joys.`:'Share this with Pip for a picnic celebration';
  return `<div class="evolution-fruit" data-level="${level}"><div class="fruit-mini ${known.includes(level)?'':'unknown'}" title="${title}">${itemIcon({kind:activeFamily,level})}<small>${known.includes(level)?f.short||f.name:'?'}</small></div>${next!==undefined?'<span class="evolution-arrow">›</span>':''}</div>`;
 }).join('');strip.scrollLeft=scroll;
}

function update(){
 if(state.reducedMotion)coins.settle();$('undo').disabled=history.length===0;$('sound').innerHTML=icon(state.sound?'sound':'mute');$('sound').setAttribute('aria-label',state.sound?'Turn sound off':'Turn sound on');$('sound').setAttribute('aria-pressed',String(state.sound));$('discovery-count').textContent=`${state.discovered.length} of ${FRUITS.length} discovered`;
 renderFamily();
 if(challenge)updateRound();
 $('pip-status').textContent=state.picnics?'A whole picnic of happiness':state.kindness>=15?'The happiest little picnic':state.kindness>=8?'Pip saved a seat for you':state.kindness>=3?'A little friendship in bloom':'A little picnic for two';document.body.classList.toggle('quiet-motion',state.reducedMotion);
}
function reward(point,text){const el=document.createElement('div');el.className='reward-pop';el.innerHTML=coinIcon(21);const label=document.createElement('span');label.textContent=text;el.append(label);const p=scene.project(point,.7);el.style.left=`${p.x}px`;el.style.top=`${p.y}px`;$('effects').append(el);setTimeout(()=>el.remove(),1900);}
function discovered(item){document.querySelector('.discovery-pop')?.remove();const el=document.createElement('div');el.className='discovery-pop';el.innerHTML=`${itemIcon(item,49)}<div><small>${family(item)==='picnic'?'A LITTLE WISH CAME TRUE':'A NEW LITTLE DISCOVERY'}</small><strong>Hello, ${itemInfo(item).name.toLowerCase()}!</strong></div>`;$('world-labels').append(el);clearTimeout(discoveryTimer);discoveryTimer=setTimeout(()=>el.remove(),3600);}
function act(fn){const before=structuredClone(state),result=fn();if(!result.ok){if(result.reason)toast(result.reason);scene?.sync();return result;}history.push(before);if(history.length>25)history.shift();scene.sync();if(result.spawned?.length)scene.releaseBasket(result.spawned);save();if(result.reward)coins.award(result.type==='share'?PLATE:result.fruit,result.reward,result.count??2);update();return result;}
function mergeFeedback(result){
 const combo=result.count>2,name=itemInfo(result.fruit).name.toLowerCase(),magic=family(result.fruit)==='picnic',noun=magic?'toy':'fruit';
 sound.discover();if(combo)sound.tone(1174.66,.24,.8,.04);
 scene.burst(result.fruit,itemInfo(result.fruit).color,Math.min(65,20+(result.count-2)*12));
 reward(result.fruit,combo?`${result.count}-${noun} combo! +${result.reward} joys`:`+${result.reward} little joys`);
 hint(combo?`${result.count} ${noun} → ${name} · ${result.multiplier}× reward · +${result.bonus} bonus joys`:`Two become one ${name}. Lovely!`);
 if(combo){scene.react();speak(result.count===3?'Right in the middle! Three little toys, one big idea.':`${result.count} together! You found the perfect little spot.`);}
 if(result.isNew){discovered(result.fruit);if(!combo)speak(magic?['','A bigger bubble, full of wishes!','Sunshine turned into lemonade!','Our bubbles made a little lunch.','Shall I pour you some pretend tea?','A whole picnic, from tiny little wishes!'][result.fruit.level]:['','','','','','','It looks like a tiny sunset.','A fruit with a crown! Very fancy.','That is a very, very big picnic!','A ruby apple, polished by the sunshine.','A little plum in the colors of twilight.','A dragon fruit! Look at those bright green tips.'][result.fruit.level]||'We made something new!');}
}
function drop(id,point){const previousKindness=state.kindness;const result=act(()=>challenge?dropChallenge(state,id,point,scene.frame):dropFruit(state,id,point,scene.frame));if(!result.ok){hint();return;}
 if(challenge){if(result.type==='merge')mergeFeedback(result);else if(result.type==='share'){sound.restore();scene.react();reward(PLATE,`+${result.reward} joys`);hint('Shared with Pip · one turn.');}else hint('One move, one turn. Keep space for the basket.');if(result.spawned?.length){sound.tone(659.25,0,.3,.03);toast(`${result.spawned.length} fresh fruit from the happy basket${result.waiting?` · ${result.waiting} waiting for space`:''}.`);}if(result.harvested){scene.react(true);scene.burst(PLATE,'#ffcf69',40);speak(`${state.challenge.harvested} of 2 watermelons! I’ll keep this one safe.`,6500);}if(result.won){scene.cancel();showResult();}return;}
 if(result.type==='merge')mergeFeedback(result);
 else if(result.type==='share'){sound.restore();scene.react(result.feast||result.hamper);scene.burst(PLATE,result.feast||result.hamper?'#f1c051':'#f19d9b',result.feast||result.hamper?65:24);reward(PLATE,`+${result.reward} little joys`);const newGift=GIFTS.filter(g=>previousKindness<g.at&&state.kindness>=g.at).at(-1);if(result.feast){speak('A whole watermelon! This is the best little picnic ever.',8000);toast('A watermelon picnic! +100 bonus joys. Keep playing as long as you like.');}else if(result.hamper){speak('A whole basket of wishes, just for our picnic!',7000);toast('A magical picnic hamper! +80 bonus joys.');}else if(newGift){speak(newGift.at===3?'I picked a flower for our table.':newGift.at===8?'I brought the tea. You brought the lovely.':'Look! Even the flowers came to our picnic.');toast(`${newGift.name} · a thank-you from Pip`);}else{speak(['For me? You are very kind.','Everything tastes better with a friend.','I saved you the imaginary biggest bite.','A tiny picnic. An enormous happy feeling.'][state.shared%4]);}hint(family(result.fruit)==='picnic'?'Pip loved that. More wishes are waiting in the bubble jar.':'Pip loved that. There is always more in the basket.');}
 else hint('A lovely spot. Everything on the mat can be moved.');
}
function add(point,merge=false){if(challenge){toast(state.challenge.status==='won'?'Picnic complete! Play again for a new challenge.':state.challenge.pending.length?`${state.challenge.pending.length} fruit waiting. Merge or share to make space.`:`The basket releases 3 fruit in ${state.challenge.untilDrop} more ${state.challenge.untilDrop===1?'turn':'turns'}.`);return{ok:false};}activeFamily='fruit';const result=act(()=>addFruit(state,point,scene.frame,{merge}));if(result.ok){if(result.type==='merge')mergeFeedback(result);else{sound.tone(523.25,0,.25,.025);hint(`A fresh ${itemInfo(result.fruit).name.toLowerCase()} for your picnic.`);scene.burst(result.fruit,itemInfo(result.fruit).color,7);}}return result;}
function makeBubble(point,merge=false){if(challenge){toast('Bubble wishes are in Free play. This picnic is a watermelon challenge.');return{ok:false};}activeFamily='picnic';const result=act(()=>addBubble(state,point,scene.frame,{merge}));if(result.ok){if(result.type==='merge')mergeFeedback(result);else{sound.tone(880,0,.35,.025);scene.burst(result.fruit,'#b9dfff',7);hint('A tiny light bubble. Match two and watch your wish grow.');}}return result;}
function undo(){if(!history.length)return;scene.cancel();const soundSetting=state.sound,motionSetting=state.reducedMotion;Object.assign(state,history.pop(),{sound:soundSetting,reducedMotion:motionSetting});coins.settle();$('effects').replaceChildren();scene.sync();update();save();hint('One little step back. Try something else.');$('pip-note').classList.add('hidden');document.querySelector('.discovery-pop')?.remove();}
function onPreview(target){
 const key=t=>t?`${t.type}:${t.kind}:${t.count}:${t.level}:${t.reward}`:'';const changed=key(preview)!==key(target);preview=target;
 const el=$('merge-preview');el.hidden=!target;el.dataset.count=target?.count??'';
 if(target&&changed){
  if(challenge&&(target.type==='move'||target.type==='blocked')){el.textContent=target.type==='blocked'?'Different fruit · choose another spot':'Move here · 1 turn';hint(target.type==='blocked'?'Only matching fruit can share a spot.':'The glow shows where your fruit will settle.');return;}
  el.innerHTML=target.type==='share'?`${icon('heart')} Share with Pip`:`${itemIcon(target,30)}<span class="merge-copy"><strong>${target.count===2?'A perfect pair':`${target.count}-${target.kind==='picnic'?'toy':'fruit'} combo`}</strong><span>${catalogue(target.kind)[target.level].name} · +${target.reward} joys${target.count>2?` <b>${target.multiplier}×</b>`:''}</span></span>`;
  hint(target.type==='share'?'Let go to share a little happiness.':`Release to combine ${target.count} highlighted toys${target.count>2?` for a ${target.multiplier}× reward`:''}.`);
 }else if(!target&&!scene?.selection)hint();
}
function placeLabels(){if(!scene)return;for(const [id,pos]of [['basket-label',BASKET],['plate-label',PLATE],['bubble-label',BUBBLE_JAR]]){const p=scene.project({...pos,y:pos.y+.083},.10),el=$(id),half=el.offsetWidth/2;el.style.left=`${Math.max(half+4,Math.min(scene.canvas.clientWidth-half-4,p.x))}px`;el.style.top=`${Math.min(scene.canvas.clientHeight-el.offsetHeight,p.y)}px`;}
 const pip=scene.selection?.type==='pip'?scene.selection.point:state.pip;const p=scene.project(pip,1.95),w=$('pip-note').offsetWidth;$('pip-note').style.left=`${Math.max(8,Math.min(scene.canvas.clientWidth-w-8,p.x-w-10))}px`;$('pip-note').style.top=`${Math.max(50,p.y-60)}px`;
 if(preview){const q=scene.project(preview.point,1.05),el=$('merge-preview'),margin=el.offsetWidth/2+8;el.style.left=`${Math.max(margin,Math.min(scene.canvas.clientWidth-margin,q.x))}px`;el.style.top=`${Math.max(el.offsetHeight+8,Math.min(scene.canvas.clientHeight-8,q.y-18))}px`;}
}
function comboGuide(){return `<div class="combo-guide"><div><svg viewBox="0 0 130 82" aria-hidden="true"><path d="M65 4v15m-5-5 5 5 5-5" stroke="#a5aa76" fill="none" stroke-width="2"/><circle cx="25" cy="45" r="13" fill="#ed6881"/><circle cx="105" cy="45" r="13" fill="#ed6881"/><circle cx="65" cy="45" r="14" fill="#fff5da" stroke="#d8ad51" stroke-width="2" stroke-dasharray="4 3"/><path d="M59 45h12m-6-6v12" stroke="#bd9140" stroke-width="2"/></svg><strong>3 fruit · 2× reward</strong><small>Two apart. Third in the middle.</small></div><div><svg viewBox="0 0 130 82" aria-hidden="true"><circle cx="28" cy="21" r="11" fill="#a478d5"/><circle cx="102" cy="21" r="11" fill="#a478d5"/><circle cx="65" cy="71" r="11" fill="#a478d5"/><circle cx="65" cy="39" r="13" fill="#fff5da" stroke="#d8ad51" stroke-width="2" stroke-dasharray="4 3"/><path d="M59 39h12m-6-6v12" stroke="#bd9140" stroke-width="2"/></svg><strong>4 fruit · 3× reward</strong><small>Three in a triangle. Fourth inside.</small></div></div>`;}
function bubbleGuide(){return `<p><strong class="bubble-help-title">A tiny bubble. A whole picnic.</strong><br>Tap or drag from the purple bubble jar to make tiny light bubbles. Match identical bubbles and treasures to grow this magical picnic. The same three- and four-toy center combos earn bigger rewards. Fruit and bubble treasures are separate families.</p><div class="bubble-sequence">${PICNIC_ITEMS.map((item,i)=>`${i?'<i>›</i>':''}<span>${picnicIcon(i,38)}${item.short}</span>`).join('')}</div><p>Share a completed hamper on Pip’s plate for 80 extra joys. You can move, undo, and save every bubble and treasure.</p>`;}
function updateRound(){const c=state.challenge;$('goal-count').textContent=`${c.harvested} / ${GOAL}`;$('goal-caption').textContent=c.status==='won'?'Both watermelons are safe. Picnic complete!':c.harvested?'One safely on the plate. One more to grow!':'Watermelons go safely onto Pip’s plate.';$('turn-count').textContent=`Turn ${c.turns}`;$('basket-countdown').textContent=c.status==='won'?'Picnic complete':c.pending.length?`${c.pending.length} waiting for space`:`Basket opens in ${c.untilDrop} ${c.untilDrop===1?'turn':'turns'}`;$('next-delivery').innerHTML=c.status==='won'?'':upcomingFruit(state).map(level=>fruitIcon(level,28)).join('');$('next-delivery').setAttribute('aria-label',c.status==='won'?'No further deliveries':`Next fruit: ${upcomingFruit(state).map(level=>FRUITS[level].name).join(', ')}`);$('next-delivery').hidden=c.status==='won';$('turn-dots').hidden=c.status==='won';$('turn-dots').innerHTML=Array.from({length:DROP_EVERY},(_,i)=>`<i class="${i<DROP_EVERY-c.untilDrop?'filled':''}"></i>`).join('');$('basket-label').querySelector('.label-sub').textContent=c.status==='won'?'picnic complete':c.pending.length?`${c.pending.length} waiting`:`3 fruit in ${c.untilDrop} ${c.untilDrop===1?'turn':'turns'}`;$('result-toggle').hidden=c.status!=='won';if(c.status!=='won'){$('round-result').hidden=true;if(scene)scene.paused=dialog.open;}}
function showResult(){scene.cancel();scene.paused=true;coins.settle();clearTimeout(toastTimer);$('toast').classList.remove('visible');$('effects').replaceChildren();document.querySelector('.discovery-pop')?.remove();$('pip-note').classList.add('hidden');$('result-fruit').innerHTML=fruitIcon(8,66)+fruitIcon(8,66);$('result-stats').innerHTML=`<span><strong>${state.challenge.turns}</strong>turns</span><span><strong>${state.score.toLocaleString()}</strong>golden joys</span><span><strong>${state.merges}</strong>merges</span>`;$('round-result').hidden=false;$('announcer').textContent=`Picnic complete! Two watermelons in ${state.challenge.turns} turns, with ${state.score} joys.`;$('play-again').focus({preventScroll:true});}
function resetPicnic(){scene.cancel();const settings={sound:state.sound,reducedMotion:state.reducedMotion};Object.assign(state,challenge?newChallenge():newPicnic(),settings);if(!challenge)introduceBubbles(state,scene.frame);coins.settle();$('effects').replaceChildren();document.querySelector('.discovery-pop')?.remove();$('round-result').hidden=true;history.length=0;scene.paused=false;scene.sync(true);activeFamily=challenge?'fruit':'picnic';update();save();dialog.close();scene.canvas.focus({preventScroll:true});hint();speak(challenge?'Two watermelons for our picnic. Let’s grow them together!':'A fresh table. A thousand little possibilities.');}
function challengeHelp(){scene.cancel();scene.paused=true;$('help-content').innerHTML=`<div class="help-fruits">${fruitIcon(8,50)}${fruitIcon(8,50)}</div><h2 id="help-title">A picnic with a purpose.</h2><p>Grow <strong>2 watermelons</strong> to finish. Each one goes safely onto Pip’s plate automatically. Coins record how well you did.</p><ol class="help-steps"><li><b>01</b><span><strong>Follow the little glow.</strong>Drag fruit across the cloth. A soft circle shows its landing spot; fruit settle into evenly spaced positions. Drop on an open spot or an identical fruit. You can also tap to pick up, then tap to place. A successful move, merge, or share uses one turn. Cancelled or invalid drops use none. Moving Pip is free.</span></li><li><b>02</b><span><strong>Combine around the center.</strong>Drop between matching fruit in the immediately neighboring positions above, below, left, or right. They become one next-stage fruit. Diagonals and distant chains do not join. Two give normal coins, three give 2×, four give 3×. Golden rings show the exact group.</span></li><li><b>03</b><span><strong>The basket opens every 3 turns.</strong>Three fruit land in open spots. Their types are shown above the mat. If there is not enough space, leftovers wait in the basket and the countdown pauses. Merge or share to clear room. An empty mat refills immediately.</span></li><li><b>04</b><span><strong>Make room, then grow again.</strong>Drop any fruit on Pip’s plate to share it. Undo takes back the whole turn, including basket arrivals and watermelon progress. There is no timer. The second watermelon ends the round.</span></li></ol><p class="keyboard-guide"><strong>Keyboard:</strong> N selects the next fruit. Arrows move to the next placement spot; Enter places; T shares the selected fruit. U undoes, Escape cancels. B checks the next delivery.</p><label class="settings-line"><input type="checkbox" id="quiet-motion" ${state.reducedMotion?'checked':''}> Quieter motion</label><button id="back-to-play" class="primary-button">Let’s grow a picnic</button><button id="reset-picnic" class="subtle-button">Start a fresh challenge</button>`;dialog.showModal();$('back-to-play').onclick=()=>dialog.close();$('quiet-motion').onchange=e=>{state.reducedMotion=e.target.checked;update();save();};$('reset-picnic').onclick=confirmReset;}
function help(){if(challenge){challengeHelp();return;}scene.cancel();scene.paused=true;$('help-content').innerHTML=`<div class="help-fruits">${fruitIcon(0,37)} + ${fruitIcon(0,37)} <span>→</span> ${fruitIcon(1,42)}</div><h2 id="help-title">A little room to play.</h2><p>There is no hurry, and no wrong way to arrange a picnic. Everything happens right on your playmat.</p><ol class="help-steps"><li><b>01</b><span><strong>Pick it up. Move it anywhere.</strong>Drag a fruit with your finger or mouse. You can also tap to pick it up, then tap to place it. Even Pip can be moved.</span></li><li><b>02</b><span><strong>Put the last fruit in the middle.</strong>Two matching fruit earn the normal reward. Leave two apart and drop a third between them for 2×. Arrange three in a loose triangle and drop a fourth inside for 3×. Every fruit you will combine is highlighted before release.</span></li><li><b>03</b><span><strong>Make it a picnic.</strong>Drag any fruit onto Pip’s plate. Kindness brings flowers, tea, and a happy friend. Share a watermelon for a big celebration.</span></li><li><b>04</b><span><strong>There is always a little more.</strong>Pick fruit from the basket. Undo takes back the last move, merge, or shared fruit. There are no timers or purchases.</span></li></ol>${comboGuide()}${bubbleGuide()}<p class="keyboard-guide"><strong>Keyboard:</strong> Focus the playmat. N picks the next toy, arrows move it (Shift moves farther), Enter puts it down. B picks from the basket. J makes a bubble. U undoes. Escape puts a held fruit back.</p><label class="settings-line"><input type="checkbox" id="quiet-motion" ${state.reducedMotion?'checked':''}> Quieter motion</label><button id="back-to-play" class="primary-button">Let’s make something lovely</button><button id="reset-picnic" class="subtle-button">Set out a fresh picnic</button>`;dialog.showModal();$('back-to-play').onclick=()=>dialog.close();$('quiet-motion').onchange=e=>{state.reducedMotion=e.target.checked;update();save();};$('reset-picnic').onclick=confirmReset;}
function confirmReset(){$('help-content').innerHTML=`<div class="help-fruits">${fruitIcon(0,46)}</div><h2 id="help-title">A fresh little table?</h2><p>This replaces this ${challenge?'challenge':'free-play picnic'} and its score. Your other mode has its own save.</p><button class="primary-button" id="keep-picnic">Keep this picnic</button><button class="subtle-button" id="confirm-reset">Yes, start a fresh picnic</button>`;$('keep-picnic').onclick=()=>dialog.close();$('confirm-reset').onclick=resetPicnic;}
$('help').onclick=help;$('close-help').onclick=()=>dialog.close();dialog.addEventListener('close',()=>{if(scene){scene.paused=false;scene.canvas.focus({preventScroll:true});}});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.x||e.clientX>r.right||e.clientY<r.y||e.clientY>r.bottom)dialog.close();}});
$('undo').onclick=undo;$('sound').onclick=()=>{state.sound=!state.sound;try{sound.setEnabled(state.sound);}catch{state.sound=false;toast('Audio is unavailable here. Your picnic still works.');}update();save();};
$('basket-label').addEventListener('pointerdown',e=>scene.startBasket(e));$('basket-label').addEventListener('click',e=>{if(e.detail===0)add({x:.18,y:.65});});
$('bubble-label').addEventListener('pointerdown',e=>scene.startJar(e));$('bubble-label').addEventListener('click',e=>{if(e.detail===0)makeBubble({x:.43,y:.65});});
$('photo').onclick=()=>{scene.cancel();const a=document.createElement('a');a.href=scene.photo();a.download='pips-fruit-picnic.png';a.click();toast('A little slice of happiness, saved.');};
document.addEventListener('visibilitychange',()=>{scene?.cancel();if(document.hidden)coins.settle();save();});window.addEventListener('pagehide',save);window.addEventListener('resize',()=>coins.settle());
document.addEventListener('keydown',()=>document.body.classList.add('keyboard-navigation'));document.addEventListener('pointerdown',()=>document.body.classList.remove('keyboard-navigation'));
// Activate a deliberate touch-button release immediately. Some mobile engines
// suppress the compatibility click just after a canvas drag; suppress a later
// native click here as well so an Undo tap can never undo two moves.
let buttonTouch=null,lastButtonTouch=null;
document.addEventListener('pointerdown',event=>{const button=event.target.closest?.('button');if(event.pointerType==='touch'&&event.isPrimary&&button&&!button.disabled&&!['basket-label','bubble-label'].includes(button.id))buttonTouch={button,id:event.pointerId,x:event.clientX,y:event.clientY};});
document.addEventListener('pointercancel',()=>{buttonTouch=null;});
document.addEventListener('pointerup',event=>{const touch=buttonTouch;if(!touch||event.pointerId!==touch.id)return;buttonTouch=null;if(touch.button===event.target.closest?.('button')&&Math.hypot(event.clientX-touch.x,event.clientY-touch.y)<10&&!touch.button.disabled){event.preventDefault();lastButtonTouch={button:touch.button,id:touch.id,x:event.clientX,y:event.clientY,at:performance.now()};touch.button.click();}});
document.addEventListener('click',event=>{if(event.isTrusted&&event.detail>0&&lastButtonTouch&&performance.now()-lastButtonTouch.at<750&&(event.pointerId===lastButtonTouch.id||Math.hypot(event.clientX-lastButtonTouch.x,event.clientY-lastButtonTouch.y)<12)){event.preventDefault();event.stopImmediatePropagation();}},true);
$('mode-link').href=challenge?'./classic.html?mode=free':'./classic.html?mode=challenge';$('mode-link').textContent=challenge?'Free play':'Challenge';$('play-again').onclick=resetPicnic;$('view-picnic').onclick=()=>{$('round-result').hidden=true;scene.paused=false;hint('Picnic complete · play again from Results.');$('result-toggle').focus();};$('result-toggle').onclick=showResult;
if(challenge){document.body.classList.add('challenge-mode');$('round-panel').hidden=false;$('goal-fruit').innerHTML=fruitIcon(8,48);$('bubble-label').hidden=true;$('basket-label').setAttribute('aria-label','Check the next basket delivery');$('picnic').setAttribute('aria-label','Picnic cloth with five rows of five snapping positions. Make two watermelons. Move or merge fruit for one turn. Three fruit arrive every three turns. N selects, arrows move between placement spots, Enter places, T shares, U undoes.');document.querySelector('.surface-heading').hidden=true;document.querySelector('.invitation').innerHTML='<span class="tiny-star">✧</span> A little plan. A lovely picnic.';document.querySelector('#plate-label .label-sub').textContent='share to make space';$('pip-note').textContent='Two watermelons for our picnic. Let’s grow them together!';hint();}
try{scene=new PicnicScene($('picnic'),state,{onDrop:drop,onAdd:add,onBubble:makeBubble,onPip:point=>{act(()=>movePip(state,point));speak('Oh! A new view of our little world.');},onPick:(type,id)=>{if(type==='jar')activeFamily='picnic';else if(type==='basket')activeFamily='fruit';else if(type==='fruit')activeFamily=family(allItems(state).find(f=>f.id===id));renderFamily();if(type==='pip')speak('Wheee!');else $('pip-note').classList.add('hidden');},onPreview,onHint:hint,onUndo:undo,onFrame:placeLabels});if(!challenge)introduceBubbles(state,scene.frame);scene.sync(true);update();save();requestAnimationFrame(()=>$('loading').classList.add('loaded'));noteTimer=setTimeout(()=>$('pip-note').classList.add('hidden'),9500);if(challenge&&state.challenge.status==='won')showResult();if(state.sound)document.addEventListener('pointerdown',()=>sound.setEnabled(true),{once:true});
 if(new URLSearchParams(location.search).has('debug'))window.__picnic={getState:()=>structuredClone(state),project:(p,y=.6)=>scene.project(p,y),getFrame:()=>({...scene.frame}),getSelection:()=>scene.selection?structuredClone(scene.selection):null,getRenderStats:()=>({...scene.renderer.info.render}),getDeliveries:()=>[...scene.fruits.values()].filter(mesh=>mesh.userData.delivery).length};
}catch(error){console.error(error);$('loading').innerHTML=`<div class="error-note"><h2>A little help for this picnic.</h2><p>This play space needs WebGL. Please use a recent browser with hardware acceleration enabled.</p><button class="primary-button" id="retry">Try again</button></div>`;$('retry').onclick=()=>location.reload();for(const id of ['basket-label','help','photo','undo'])$(id).disabled=true;}
